<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_anlaggning',
		'title' => 'Anläggning',
		'fields' => array (
			array (
				'key' => 'field_560265ebe033c',
				'label' => 'Kontaktinformation',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5602666ae033d',
				'label' => 'Besöksadress',
				'name' => 'facility-address',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_560266aee033e',
						'label' => 'Avdelning',
						'name' => 'department-name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_560266c4e033f',
						'label' => 'Adress',
						'name' => 'department-address',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'formatting' => 'br',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till adress',
			),
			array (
				'key' => 'field_560266d9e0340',
				'label' => 'Telefonnummer',
				'name' => 'facility-telephone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_560266f1e0341',
				'label' => 'Faxnummer',
				'name' => 'facility-telefax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_560266fce0342',
				'label' => 'E-post',
				'name' => 'facility-email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_56026714e0343',
				'label' => 'Karta',
				'name' => 'facility-map',
				'type' => 'google_map',
				'center_lat' => '59.3351887',
				'center_lng' => '18.028736',
				'zoom' => 11,
				'height' => '',
			),
			array (
				'key' => 'field_5602678ce0345',
				'label' => 'Öppettider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56026770e0344',
				'label' => 'Avdelningar',
				'name' => 'facility-departments',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_560267abe0346',
						'label' => 'Namn',
						'name' => 'department-name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_560267bfe0347',
						'label' => 'Öppettider',
						'name' => 'department-openhours',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_560267e0e0348',
								'label' => 'Text',
								'name' => 'openhours-text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_560267f5e0349',
								'label' => 'Tid',
								'name' => 'openhours-time',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Lägg till tid',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Lägg till avdelning',
			),
			array (
				'key' => 'field_5602682ce034b',
				'label' => 'Extra information',
				'name' => 'facility-extra-information',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'facility',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_anlaggningsval',
		'title' => 'Anläggningsval',
		'fields' => array (
			array (
				'key' => 'field_56026b68043d0',
				'label' => 'Välj anläggning',
				'name' => 'facility-choice',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'facility',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56027655b8f2f',
				'label' => 'Kontaktformulär',
				'name' => 'facility-contact-form',
				'type' => 'acf_cf7',
				'allow_null' => 0,
				'multiple' => 0,
				'disable' => array (
					0 => 0,
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'facility-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_fordonsurval',
		'title' => 'Fordonsurval',
		'fields' => array (
			array (
				'key' => 'field_56028068dfc02',
				'label' => 'Välj fordonsurval',
				'name' => 'assortment-choice',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'assortment',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'assortment-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_installningar',
		'title' => 'Inställningar',
		'fields' => array (
			array (
				'key' => 'field_55fac48b39636',
				'label' => 'Generella inställningar',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55fabf269b1f4',
				'label' => 'Logotyp',
				'name' => 'settings-logotype',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55fac0349b1f5',
				'label' => 'Bakgrund',
				'name' => 'settings-background',
				'type' => 'select',
				'choices' => array (
					'color' => 'Färg',
					'image' => 'Bild',
				),
				'default_value' => 'color',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55fac05a9b1f6',
				'label' => 'Bakgrundsbild',
				'name' => 'settings-background-image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55fac0349b1f5',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55fac0679b1f7',
				'label' => 'Bakgrundsfärg',
				'name' => 'settings-background-color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55fac0349b1f5',
							'operator' => '==',
							'value' => 'color',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#f0f0f0',
			),
			array (
				'key' => 'field_560227c550504',
				'label' => 'Sidhuvud',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55fac4a939637',
				'label' => 'Märken',
				'name' => 'settings-brands',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_55faccc339638',
						'label' => 'Logotyp',
						'name' => 'brands-logotyp',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_55faccee39639',
						'label' => 'Länk',
						'name' => 'brands-link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55faccfb3963a',
						'label' => 'Länkbeteende',
						'name' => 'brands-target',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'_self' => 'Öppna i samma fönster',
							'_blank' => 'Öppna i ett nytt fönster',
						),
						'default_value' => '_self',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till märke',
			),
			array (
				'key' => 'field_55facfbb522e1',
				'label' => 'Facebook-sida',
				'name' => 'settings-facebookpage',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_560282b95f96e',
				'label' => 'Sidfot',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_560282c95f96f',
				'label' => 'Anläggningar',
				'name' => 'settings-facilities',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'facility',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_5602337b3c39b',
				'label' => 'Avancerade inställningar',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_560233943c39c',
				'label' => 'BytBil Alias',
				'name' => 'settings-bbalias',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-installningar',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_personal',
		'title' => 'Personal',
		'fields' => array (
			array (
				'key' => 'field_5603cdaba5221',
				'label' => 'Bild',
				'name' => 'employee-image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5603cd99a5220',
				'label' => 'Titel',
				'name' => 'employee-title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5603cdbca5222',
				'label' => 'Telefon',
				'name' => 'employee-phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5603cdc7a5223',
				'label' => 'E-post',
				'name' => 'employee-email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5603cdfda5224',
				'label' => 'Anläggning',
				'name' => 'employee-facility',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'facility',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'employee',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_personallista',
		'title' => 'Personallista',
		'fields' => array (
			array (
				'key' => 'field_5603cf5eea891',
				'label' => 'Rubrik',
				'name' => 'employee-list-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5603cf8dea892',
				'label' => 'Personal',
				'name' => 'employee-list-employees',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'employee',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'employee-list',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_personalval',
		'title' => 'Personalval',
		'fields' => array (
			array (
				'key' => 'field_5603d01d04173',
				'label' => 'Visa personal',
				'name' => 'employee-choice',
				'type' => 'select',
				'choices' => array (
					'employee-list' => 'Personallista',
					'employees' => 'Välj personal',
				),
				'default_value' => 'employee-list',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5603d63763f2a',
				'label' => 'Personallista',
				'name' => 'employee-list_2',
				'type' => 'relationship',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5603d01d04173',
							'operator' => '==',
							'value' => 'employee-list',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'object',
				'post_type' => array (
					0 => 'employee-list',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
            array(
                'key' => 'field_5603d63763f2b',
                'label' => 'Visa listans rubrik',
                'name' => 'employee-list-show-header',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
                'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5603d01d04173',
							'operator' => '==',
							'value' => 'employee-list',
						),
					),
					'allorany' => 'all',
				),
            ),
			array (
				'key' => 'field_5603d0b404175',
				'label' => 'Välj personal',
				'name' => 'employee-employees',
				'type' => 'relationship',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5603d01d04173',
							'operator' => '==',
							'value' => 'employees',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'object',
				'post_type' => array (
					0 => 'employee',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_5603d10fcdb95',
				'label' => 'Visa anläggningsinformation',
				'name' => 'employee-facilities',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'facility',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'employees-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_puffar',
		'title' => 'Puffar',
		'fields' => array (
			array (
				'key' => 'field_560235f286ca0',
				'label' => 'Innehåll',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56023804ae15e',
				'label' => 'Text',
				'name' => 'plug-text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5602367dae159',
				'label' => 'Pufftyp',
				'name' => 'plug-type',
				'type' => 'select',
				'choices' => array (
					'small' => 'Liten bild',
					'big' => 'Stor bild',
					'none' => 'Enbart text',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023703ae15a',
				'label' => 'Bildtyp',
				'name' => 'plug-image-type',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5602367dae159',
							'operator' => '!=',
							'value' => 'none',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'icon' => 'Ikon',
					'image' => 'Egen bild',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023775ae15b',
				'label' => 'Ikon',
				'name' => 'plug-icon',
				'type' => 'font-awesome',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5602367dae159',
							'operator' => '!=',
							'value' => 'none',
						),
						array (
							'field' => 'field_56023703ae15a',
							'operator' => '==',
							'value' => 'icon',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'fa-circle',
				'save_format' => 'class',
				'allow_null' => 0,
				'enqueue_fa' => 0,
				'choices' => array (
					'null' => '- Select -',
					'fa-500px' => ' fa-500px',
					'fa-adjust' => ' fa-adjust',
					'fa-adn' => ' fa-adn',
					'fa-align-center' => ' fa-align-center',
					'fa-align-justify' => ' fa-align-justify',
					'fa-align-left' => ' fa-align-left',
					'fa-align-right' => ' fa-align-right',
					'fa-amazon' => ' fa-amazon',
					'fa-ambulance' => ' fa-ambulance',
					'fa-anchor' => ' fa-anchor',
					'fa-android' => ' fa-android',
					'fa-angellist' => ' fa-angellist',
					'fa-angle-double-down' => ' fa-angle-double-down',
					'fa-angle-double-left' => ' fa-angle-double-left',
					'fa-angle-double-right' => ' fa-angle-double-right',
					'fa-angle-double-up' => ' fa-angle-double-up',
					'fa-angle-down' => ' fa-angle-down',
					'fa-angle-left' => ' fa-angle-left',
					'fa-angle-right' => ' fa-angle-right',
					'fa-angle-up' => ' fa-angle-up',
					'fa-apple' => ' fa-apple',
					'fa-archive' => ' fa-archive',
					'fa-area-chart' => ' fa-area-chart',
					'fa-arrow-circle-down' => ' fa-arrow-circle-down',
					'fa-arrow-circle-left' => ' fa-arrow-circle-left',
					'fa-arrow-circle-o-down' => ' fa-arrow-circle-o-down',
					'fa-arrow-circle-o-left' => ' fa-arrow-circle-o-left',
					'fa-arrow-circle-o-right' => ' fa-arrow-circle-o-right',
					'fa-arrow-circle-o-up' => ' fa-arrow-circle-o-up',
					'fa-arrow-circle-right' => ' fa-arrow-circle-right',
					'fa-arrow-circle-up' => ' fa-arrow-circle-up',
					'fa-arrow-down' => ' fa-arrow-down',
					'fa-arrow-left' => ' fa-arrow-left',
					'fa-arrow-right' => ' fa-arrow-right',
					'fa-arrow-up' => ' fa-arrow-up',
					'fa-arrows' => ' fa-arrows',
					'fa-arrows-alt' => ' fa-arrows-alt',
					'fa-arrows-h' => ' fa-arrows-h',
					'fa-arrows-v' => ' fa-arrows-v',
					'fa-asterisk' => ' fa-asterisk',
					'fa-at' => ' fa-at',
					'fa-backward' => ' fa-backward',
					'fa-balance-scale' => ' fa-balance-scale',
					'fa-ban' => ' fa-ban',
					'fa-bar-chart' => ' fa-bar-chart',
					'fa-barcode' => ' fa-barcode',
					'fa-bars' => ' fa-bars',
					'fa-battery-empty' => ' fa-battery-empty',
					'fa-battery-full' => ' fa-battery-full',
					'fa-battery-half' => ' fa-battery-half',
					'fa-battery-quarter' => ' fa-battery-quarter',
					'fa-battery-three-quarters' => ' fa-battery-three-quarters',
					'fa-bed' => ' fa-bed',
					'fa-beer' => ' fa-beer',
					'fa-behance' => ' fa-behance',
					'fa-behance-square' => ' fa-behance-square',
					'fa-bell' => ' fa-bell',
					'fa-bell-o' => ' fa-bell-o',
					'fa-bell-slash' => ' fa-bell-slash',
					'fa-bell-slash-o' => ' fa-bell-slash-o',
					'fa-bicycle' => ' fa-bicycle',
					'fa-binoculars' => ' fa-binoculars',
					'fa-birthday-cake' => ' fa-birthday-cake',
					'fa-bitbucket' => ' fa-bitbucket',
					'fa-bitbucket-square' => ' fa-bitbucket-square',
					'fa-black-tie' => ' fa-black-tie',
					'fa-bold' => ' fa-bold',
					'fa-bolt' => ' fa-bolt',
					'fa-bomb' => ' fa-bomb',
					'fa-book' => ' fa-book',
					'fa-bookmark' => ' fa-bookmark',
					'fa-bookmark-o' => ' fa-bookmark-o',
					'fa-briefcase' => ' fa-briefcase',
					'fa-btc' => ' fa-btc',
					'fa-bug' => ' fa-bug',
					'fa-building' => ' fa-building',
					'fa-building-o' => ' fa-building-o',
					'fa-bullhorn' => ' fa-bullhorn',
					'fa-bullseye' => ' fa-bullseye',
					'fa-bus' => ' fa-bus',
					'fa-buysellads' => ' fa-buysellads',
					'fa-calculator' => ' fa-calculator',
					'fa-calendar' => ' fa-calendar',
					'fa-calendar-check-o' => ' fa-calendar-check-o',
					'fa-calendar-minus-o' => ' fa-calendar-minus-o',
					'fa-calendar-o' => ' fa-calendar-o',
					'fa-calendar-plus-o' => ' fa-calendar-plus-o',
					'fa-calendar-times-o' => ' fa-calendar-times-o',
					'fa-camera' => ' fa-camera',
					'fa-camera-retro' => ' fa-camera-retro',
					'fa-car' => ' fa-car',
					'fa-caret-down' => ' fa-caret-down',
					'fa-caret-left' => ' fa-caret-left',
					'fa-caret-right' => ' fa-caret-right',
					'fa-caret-square-o-down' => ' fa-caret-square-o-down',
					'fa-caret-square-o-left' => ' fa-caret-square-o-left',
					'fa-caret-square-o-right' => ' fa-caret-square-o-right',
					'fa-caret-square-o-up' => ' fa-caret-square-o-up',
					'fa-caret-up' => ' fa-caret-up',
					'fa-cart-arrow-down' => ' fa-cart-arrow-down',
					'fa-cart-plus' => ' fa-cart-plus',
					'fa-cc' => ' fa-cc',
					'fa-cc-amex' => ' fa-cc-amex',
					'fa-cc-diners-club' => ' fa-cc-diners-club',
					'fa-cc-discover' => ' fa-cc-discover',
					'fa-cc-jcb' => ' fa-cc-jcb',
					'fa-cc-mastercard' => ' fa-cc-mastercard',
					'fa-cc-paypal' => ' fa-cc-paypal',
					'fa-cc-stripe' => ' fa-cc-stripe',
					'fa-cc-visa' => ' fa-cc-visa',
					'fa-certificate' => ' fa-certificate',
					'fa-chain-broken' => ' fa-chain-broken',
					'fa-check' => ' fa-check',
					'fa-check-circle' => ' fa-check-circle',
					'fa-check-circle-o' => ' fa-check-circle-o',
					'fa-check-square' => ' fa-check-square',
					'fa-check-square-o' => ' fa-check-square-o',
					'fa-chevron-circle-down' => ' fa-chevron-circle-down',
					'fa-chevron-circle-left' => ' fa-chevron-circle-left',
					'fa-chevron-circle-right' => ' fa-chevron-circle-right',
					'fa-chevron-circle-up' => ' fa-chevron-circle-up',
					'fa-chevron-down' => ' fa-chevron-down',
					'fa-chevron-left' => ' fa-chevron-left',
					'fa-chevron-right' => ' fa-chevron-right',
					'fa-chevron-up' => ' fa-chevron-up',
					'fa-child' => ' fa-child',
					'fa-chrome' => ' fa-chrome',
					'fa-circle' => ' fa-circle',
					'fa-circle-o' => ' fa-circle-o',
					'fa-circle-o-notch' => ' fa-circle-o-notch',
					'fa-circle-thin' => ' fa-circle-thin',
					'fa-clipboard' => ' fa-clipboard',
					'fa-clock-o' => ' fa-clock-o',
					'fa-clone' => ' fa-clone',
					'fa-cloud' => ' fa-cloud',
					'fa-cloud-download' => ' fa-cloud-download',
					'fa-cloud-upload' => ' fa-cloud-upload',
					'fa-code' => ' fa-code',
					'fa-code-fork' => ' fa-code-fork',
					'fa-codepen' => ' fa-codepen',
					'fa-coffee' => ' fa-coffee',
					'fa-cog' => ' fa-cog',
					'fa-cogs' => ' fa-cogs',
					'fa-columns' => ' fa-columns',
					'fa-comment' => ' fa-comment',
					'fa-comment-o' => ' fa-comment-o',
					'fa-commenting' => ' fa-commenting',
					'fa-commenting-o' => ' fa-commenting-o',
					'fa-comments' => ' fa-comments',
					'fa-comments-o' => ' fa-comments-o',
					'fa-compass' => ' fa-compass',
					'fa-compress' => ' fa-compress',
					'fa-connectdevelop' => ' fa-connectdevelop',
					'fa-contao' => ' fa-contao',
					'fa-copyright' => ' fa-copyright',
					'fa-creative-commons' => ' fa-creative-commons',
					'fa-credit-card' => ' fa-credit-card',
					'fa-crop' => ' fa-crop',
					'fa-crosshairs' => ' fa-crosshairs',
					'fa-css3' => ' fa-css3',
					'fa-cube' => ' fa-cube',
					'fa-cubes' => ' fa-cubes',
					'fa-cutlery' => ' fa-cutlery',
					'fa-dashcube' => ' fa-dashcube',
					'fa-database' => ' fa-database',
					'fa-delicious' => ' fa-delicious',
					'fa-desktop' => ' fa-desktop',
					'fa-deviantart' => ' fa-deviantart',
					'fa-diamond' => ' fa-diamond',
					'fa-digg' => ' fa-digg',
					'fa-dot-circle-o' => ' fa-dot-circle-o',
					'fa-download' => ' fa-download',
					'fa-dribbble' => ' fa-dribbble',
					'fa-dropbox' => ' fa-dropbox',
					'fa-drupal' => ' fa-drupal',
					'fa-eject' => ' fa-eject',
					'fa-ellipsis-h' => ' fa-ellipsis-h',
					'fa-ellipsis-v' => ' fa-ellipsis-v',
					'fa-empire' => ' fa-empire',
					'fa-envelope' => ' fa-envelope',
					'fa-envelope-o' => ' fa-envelope-o',
					'fa-envelope-square' => ' fa-envelope-square',
					'fa-eraser' => ' fa-eraser',
					'fa-eur' => ' fa-eur',
					'fa-exchange' => ' fa-exchange',
					'fa-exclamation' => ' fa-exclamation',
					'fa-exclamation-circle' => ' fa-exclamation-circle',
					'fa-exclamation-triangle' => ' fa-exclamation-triangle',
					'fa-expand' => ' fa-expand',
					'fa-expeditedssl' => ' fa-expeditedssl',
					'fa-external-link' => ' fa-external-link',
					'fa-external-link-square' => ' fa-external-link-square',
					'fa-eye' => ' fa-eye',
					'fa-eye-slash' => ' fa-eye-slash',
					'fa-eyedropper' => ' fa-eyedropper',
					'fa-facebook' => ' fa-facebook',
					'fa-facebook-official' => ' fa-facebook-official',
					'fa-facebook-square' => ' fa-facebook-square',
					'fa-fast-backward' => ' fa-fast-backward',
					'fa-fast-forward' => ' fa-fast-forward',
					'fa-fax' => ' fa-fax',
					'fa-female' => ' fa-female',
					'fa-fighter-jet' => ' fa-fighter-jet',
					'fa-file' => ' fa-file',
					'fa-file-archive-o' => ' fa-file-archive-o',
					'fa-file-audio-o' => ' fa-file-audio-o',
					'fa-file-code-o' => ' fa-file-code-o',
					'fa-file-excel-o' => ' fa-file-excel-o',
					'fa-file-image-o' => ' fa-file-image-o',
					'fa-file-o' => ' fa-file-o',
					'fa-file-pdf-o' => ' fa-file-pdf-o',
					'fa-file-powerpoint-o' => ' fa-file-powerpoint-o',
					'fa-file-text' => ' fa-file-text',
					'fa-file-text-o' => ' fa-file-text-o',
					'fa-file-video-o' => ' fa-file-video-o',
					'fa-file-word-o' => ' fa-file-word-o',
					'fa-files-o' => ' fa-files-o',
					'fa-film' => ' fa-film',
					'fa-filter' => ' fa-filter',
					'fa-fire' => ' fa-fire',
					'fa-fire-extinguisher' => ' fa-fire-extinguisher',
					'fa-firefox' => ' fa-firefox',
					'fa-flag' => ' fa-flag',
					'fa-flag-checkered' => ' fa-flag-checkered',
					'fa-flag-o' => ' fa-flag-o',
					'fa-flask' => ' fa-flask',
					'fa-flickr' => ' fa-flickr',
					'fa-floppy-o' => ' fa-floppy-o',
					'fa-folder' => ' fa-folder',
					'fa-folder-o' => ' fa-folder-o',
					'fa-folder-open' => ' fa-folder-open',
					'fa-folder-open-o' => ' fa-folder-open-o',
					'fa-font' => ' fa-font',
					'fa-fonticons' => ' fa-fonticons',
					'fa-forumbee' => ' fa-forumbee',
					'fa-forward' => ' fa-forward',
					'fa-foursquare' => ' fa-foursquare',
					'fa-frown-o' => ' fa-frown-o',
					'fa-futbol-o' => ' fa-futbol-o',
					'fa-gamepad' => ' fa-gamepad',
					'fa-gavel' => ' fa-gavel',
					'fa-gbp' => ' fa-gbp',
					'fa-genderless' => ' fa-genderless',
					'fa-get-pocket' => ' fa-get-pocket',
					'fa-gg' => ' fa-gg',
					'fa-gg-circle' => ' fa-gg-circle',
					'fa-gift' => ' fa-gift',
					'fa-git' => ' fa-git',
					'fa-git-square' => ' fa-git-square',
					'fa-github' => ' fa-github',
					'fa-github-alt' => ' fa-github-alt',
					'fa-github-square' => ' fa-github-square',
					'fa-glass' => ' fa-glass',
					'fa-globe' => ' fa-globe',
					'fa-google' => ' fa-google',
					'fa-google-plus' => ' fa-google-plus',
					'fa-google-plus-square' => ' fa-google-plus-square',
					'fa-google-wallet' => ' fa-google-wallet',
					'fa-graduation-cap' => ' fa-graduation-cap',
					'fa-gratipay' => ' fa-gratipay',
					'fa-h-square' => ' fa-h-square',
					'fa-hacker-news' => ' fa-hacker-news',
					'fa-hand-lizard-o' => ' fa-hand-lizard-o',
					'fa-hand-o-down' => ' fa-hand-o-down',
					'fa-hand-o-left' => ' fa-hand-o-left',
					'fa-hand-o-right' => ' fa-hand-o-right',
					'fa-hand-o-up' => ' fa-hand-o-up',
					'fa-hand-paper-o' => ' fa-hand-paper-o',
					'fa-hand-peace-o' => ' fa-hand-peace-o',
					'fa-hand-pointer-o' => ' fa-hand-pointer-o',
					'fa-hand-rock-o' => ' fa-hand-rock-o',
					'fa-hand-scissors-o' => ' fa-hand-scissors-o',
					'fa-hand-spock-o' => ' fa-hand-spock-o',
					'fa-hdd-o' => ' fa-hdd-o',
					'fa-header' => ' fa-header',
					'fa-headphones' => ' fa-headphones',
					'fa-heart' => ' fa-heart',
					'fa-heart-o' => ' fa-heart-o',
					'fa-heartbeat' => ' fa-heartbeat',
					'fa-history' => ' fa-history',
					'fa-home' => ' fa-home',
					'fa-hospital-o' => ' fa-hospital-o',
					'fa-hourglass' => ' fa-hourglass',
					'fa-hourglass-end' => ' fa-hourglass-end',
					'fa-hourglass-half' => ' fa-hourglass-half',
					'fa-hourglass-o' => ' fa-hourglass-o',
					'fa-hourglass-start' => ' fa-hourglass-start',
					'fa-houzz' => ' fa-houzz',
					'fa-html5' => ' fa-html5',
					'fa-i-cursor' => ' fa-i-cursor',
					'fa-ils' => ' fa-ils',
					'fa-inbox' => ' fa-inbox',
					'fa-indent' => ' fa-indent',
					'fa-industry' => ' fa-industry',
					'fa-info' => ' fa-info',
					'fa-info-circle' => ' fa-info-circle',
					'fa-inr' => ' fa-inr',
					'fa-instagram' => ' fa-instagram',
					'fa-internet-explorer' => ' fa-internet-explorer',
					'fa-ioxhost' => ' fa-ioxhost',
					'fa-italic' => ' fa-italic',
					'fa-joomla' => ' fa-joomla',
					'fa-jpy' => ' fa-jpy',
					'fa-jsfiddle' => ' fa-jsfiddle',
					'fa-key' => ' fa-key',
					'fa-keyboard-o' => ' fa-keyboard-o',
					'fa-krw' => ' fa-krw',
					'fa-language' => ' fa-language',
					'fa-laptop' => ' fa-laptop',
					'fa-lastfm' => ' fa-lastfm',
					'fa-lastfm-square' => ' fa-lastfm-square',
					'fa-leaf' => ' fa-leaf',
					'fa-leanpub' => ' fa-leanpub',
					'fa-lemon-o' => ' fa-lemon-o',
					'fa-level-down' => ' fa-level-down',
					'fa-level-up' => ' fa-level-up',
					'fa-life-ring' => ' fa-life-ring',
					'fa-lightbulb-o' => ' fa-lightbulb-o',
					'fa-line-chart' => ' fa-line-chart',
					'fa-link' => ' fa-link',
					'fa-linkedin' => ' fa-linkedin',
					'fa-linkedin-square' => ' fa-linkedin-square',
					'fa-linux' => ' fa-linux',
					'fa-list' => ' fa-list',
					'fa-list-alt' => ' fa-list-alt',
					'fa-list-ol' => ' fa-list-ol',
					'fa-list-ul' => ' fa-list-ul',
					'fa-location-arrow' => ' fa-location-arrow',
					'fa-lock' => ' fa-lock',
					'fa-long-arrow-down' => ' fa-long-arrow-down',
					'fa-long-arrow-left' => ' fa-long-arrow-left',
					'fa-long-arrow-right' => ' fa-long-arrow-right',
					'fa-long-arrow-up' => ' fa-long-arrow-up',
					'fa-magic' => ' fa-magic',
					'fa-magnet' => ' fa-magnet',
					'fa-male' => ' fa-male',
					'fa-map' => ' fa-map',
					'fa-map-marker' => ' fa-map-marker',
					'fa-map-o' => ' fa-map-o',
					'fa-map-pin' => ' fa-map-pin',
					'fa-map-signs' => ' fa-map-signs',
					'fa-mars' => ' fa-mars',
					'fa-mars-double' => ' fa-mars-double',
					'fa-mars-stroke' => ' fa-mars-stroke',
					'fa-mars-stroke-h' => ' fa-mars-stroke-h',
					'fa-mars-stroke-v' => ' fa-mars-stroke-v',
					'fa-maxcdn' => ' fa-maxcdn',
					'fa-meanpath' => ' fa-meanpath',
					'fa-medium' => ' fa-medium',
					'fa-medkit' => ' fa-medkit',
					'fa-meh-o' => ' fa-meh-o',
					'fa-mercury' => ' fa-mercury',
					'fa-microphone' => ' fa-microphone',
					'fa-microphone-slash' => ' fa-microphone-slash',
					'fa-minus' => ' fa-minus',
					'fa-minus-circle' => ' fa-minus-circle',
					'fa-minus-square' => ' fa-minus-square',
					'fa-minus-square-o' => ' fa-minus-square-o',
					'fa-mobile' => ' fa-mobile',
					'fa-money' => ' fa-money',
					'fa-moon-o' => ' fa-moon-o',
					'fa-motorcycle' => ' fa-motorcycle',
					'fa-mouse-pointer' => ' fa-mouse-pointer',
					'fa-music' => ' fa-music',
					'fa-neuter' => ' fa-neuter',
					'fa-newspaper-o' => ' fa-newspaper-o',
					'fa-object-group' => ' fa-object-group',
					'fa-object-ungroup' => ' fa-object-ungroup',
					'fa-odnoklassniki' => ' fa-odnoklassniki',
					'fa-odnoklassniki-square' => ' fa-odnoklassniki-square',
					'fa-opencart' => ' fa-opencart',
					'fa-openid' => ' fa-openid',
					'fa-opera' => ' fa-opera',
					'fa-optin-monster' => ' fa-optin-monster',
					'fa-outdent' => ' fa-outdent',
					'fa-pagelines' => ' fa-pagelines',
					'fa-paint-brush' => ' fa-paint-brush',
					'fa-paper-plane' => ' fa-paper-plane',
					'fa-paper-plane-o' => ' fa-paper-plane-o',
					'fa-paperclip' => ' fa-paperclip',
					'fa-paragraph' => ' fa-paragraph',
					'fa-pause' => ' fa-pause',
					'fa-paw' => ' fa-paw',
					'fa-paypal' => ' fa-paypal',
					'fa-pencil' => ' fa-pencil',
					'fa-pencil-square' => ' fa-pencil-square',
					'fa-pencil-square-o' => ' fa-pencil-square-o',
					'fa-phone' => ' fa-phone',
					'fa-phone-square' => ' fa-phone-square',
					'fa-picture-o' => ' fa-picture-o',
					'fa-pie-chart' => ' fa-pie-chart',
					'fa-pied-piper' => ' fa-pied-piper',
					'fa-pied-piper-alt' => ' fa-pied-piper-alt',
					'fa-pinterest' => ' fa-pinterest',
					'fa-pinterest-p' => ' fa-pinterest-p',
					'fa-pinterest-square' => ' fa-pinterest-square',
					'fa-plane' => ' fa-plane',
					'fa-play' => ' fa-play',
					'fa-play-circle' => ' fa-play-circle',
					'fa-play-circle-o' => ' fa-play-circle-o',
					'fa-plug' => ' fa-plug',
					'fa-plus' => ' fa-plus',
					'fa-plus-circle' => ' fa-plus-circle',
					'fa-plus-square' => ' fa-plus-square',
					'fa-plus-square-o' => ' fa-plus-square-o',
					'fa-power-off' => ' fa-power-off',
					'fa-print' => ' fa-print',
					'fa-puzzle-piece' => ' fa-puzzle-piece',
					'fa-qq' => ' fa-qq',
					'fa-qrcode' => ' fa-qrcode',
					'fa-question' => ' fa-question',
					'fa-question-circle' => ' fa-question-circle',
					'fa-quote-left' => ' fa-quote-left',
					'fa-quote-right' => ' fa-quote-right',
					'fa-random' => ' fa-random',
					'fa-rebel' => ' fa-rebel',
					'fa-recycle' => ' fa-recycle',
					'fa-reddit' => ' fa-reddit',
					'fa-reddit-square' => ' fa-reddit-square',
					'fa-refresh' => ' fa-refresh',
					'fa-registered' => ' fa-registered',
					'fa-renren' => ' fa-renren',
					'fa-repeat' => ' fa-repeat',
					'fa-reply' => ' fa-reply',
					'fa-reply-all' => ' fa-reply-all',
					'fa-retweet' => ' fa-retweet',
					'fa-road' => ' fa-road',
					'fa-rocket' => ' fa-rocket',
					'fa-rss' => ' fa-rss',
					'fa-rss-square' => ' fa-rss-square',
					'fa-rub' => ' fa-rub',
					'fa-safari' => ' fa-safari',
					'fa-scissors' => ' fa-scissors',
					'fa-search' => ' fa-search',
					'fa-search-minus' => ' fa-search-minus',
					'fa-search-plus' => ' fa-search-plus',
					'fa-sellsy' => ' fa-sellsy',
					'fa-server' => ' fa-server',
					'fa-share' => ' fa-share',
					'fa-share-alt' => ' fa-share-alt',
					'fa-share-alt-square' => ' fa-share-alt-square',
					'fa-share-square' => ' fa-share-square',
					'fa-share-square-o' => ' fa-share-square-o',
					'fa-shield' => ' fa-shield',
					'fa-ship' => ' fa-ship',
					'fa-shirtsinbulk' => ' fa-shirtsinbulk',
					'fa-shopping-cart' => ' fa-shopping-cart',
					'fa-sign-in' => ' fa-sign-in',
					'fa-sign-out' => ' fa-sign-out',
					'fa-signal' => ' fa-signal',
					'fa-simplybuilt' => ' fa-simplybuilt',
					'fa-sitemap' => ' fa-sitemap',
					'fa-skyatlas' => ' fa-skyatlas',
					'fa-skype' => ' fa-skype',
					'fa-slack' => ' fa-slack',
					'fa-sliders' => ' fa-sliders',
					'fa-slideshare' => ' fa-slideshare',
					'fa-smile-o' => ' fa-smile-o',
					'fa-sort' => ' fa-sort',
					'fa-sort-alpha-asc' => ' fa-sort-alpha-asc',
					'fa-sort-alpha-desc' => ' fa-sort-alpha-desc',
					'fa-sort-amount-asc' => ' fa-sort-amount-asc',
					'fa-sort-amount-desc' => ' fa-sort-amount-desc',
					'fa-sort-asc' => ' fa-sort-asc',
					'fa-sort-desc' => ' fa-sort-desc',
					'fa-sort-numeric-asc' => ' fa-sort-numeric-asc',
					'fa-sort-numeric-desc' => ' fa-sort-numeric-desc',
					'fa-soundcloud' => ' fa-soundcloud',
					'fa-space-shuttle' => ' fa-space-shuttle',
					'fa-spinner' => ' fa-spinner',
					'fa-spoon' => ' fa-spoon',
					'fa-spotify' => ' fa-spotify',
					'fa-square' => ' fa-square',
					'fa-square-o' => ' fa-square-o',
					'fa-stack-exchange' => ' fa-stack-exchange',
					'fa-stack-overflow' => ' fa-stack-overflow',
					'fa-star' => ' fa-star',
					'fa-star-half' => ' fa-star-half',
					'fa-star-half-o' => ' fa-star-half-o',
					'fa-star-o' => ' fa-star-o',
					'fa-steam' => ' fa-steam',
					'fa-steam-square' => ' fa-steam-square',
					'fa-step-backward' => ' fa-step-backward',
					'fa-step-forward' => ' fa-step-forward',
					'fa-stethoscope' => ' fa-stethoscope',
					'fa-sticky-note' => ' fa-sticky-note',
					'fa-sticky-note-o' => ' fa-sticky-note-o',
					'fa-stop' => ' fa-stop',
					'fa-street-view' => ' fa-street-view',
					'fa-strikethrough' => ' fa-strikethrough',
					'fa-stumbleupon' => ' fa-stumbleupon',
					'fa-stumbleupon-circle' => ' fa-stumbleupon-circle',
					'fa-subscript' => ' fa-subscript',
					'fa-subway' => ' fa-subway',
					'fa-suitcase' => ' fa-suitcase',
					'fa-sun-o' => ' fa-sun-o',
					'fa-superscript' => ' fa-superscript',
					'fa-table' => ' fa-table',
					'fa-tablet' => ' fa-tablet',
					'fa-tachometer' => ' fa-tachometer',
					'fa-tag' => ' fa-tag',
					'fa-tags' => ' fa-tags',
					'fa-tasks' => ' fa-tasks',
					'fa-taxi' => ' fa-taxi',
					'fa-television' => ' fa-television',
					'fa-tencent-weibo' => ' fa-tencent-weibo',
					'fa-terminal' => ' fa-terminal',
					'fa-text-height' => ' fa-text-height',
					'fa-text-width' => ' fa-text-width',
					'fa-th' => ' fa-th',
					'fa-th-large' => ' fa-th-large',
					'fa-th-list' => ' fa-th-list',
					'fa-thumb-tack' => ' fa-thumb-tack',
					'fa-thumbs-down' => ' fa-thumbs-down',
					'fa-thumbs-o-down' => ' fa-thumbs-o-down',
					'fa-thumbs-o-up' => ' fa-thumbs-o-up',
					'fa-thumbs-up' => ' fa-thumbs-up',
					'fa-ticket' => ' fa-ticket',
					'fa-times' => ' fa-times',
					'fa-times-circle' => ' fa-times-circle',
					'fa-times-circle-o' => ' fa-times-circle-o',
					'fa-tint' => ' fa-tint',
					'fa-toggle-off' => ' fa-toggle-off',
					'fa-toggle-on' => ' fa-toggle-on',
					'fa-trademark' => ' fa-trademark',
					'fa-train' => ' fa-train',
					'fa-transgender' => ' fa-transgender',
					'fa-transgender-alt' => ' fa-transgender-alt',
					'fa-trash' => ' fa-trash',
					'fa-trash-o' => ' fa-trash-o',
					'fa-tree' => ' fa-tree',
					'fa-trello' => ' fa-trello',
					'fa-tripadvisor' => ' fa-tripadvisor',
					'fa-trophy' => ' fa-trophy',
					'fa-truck' => ' fa-truck',
					'fa-try' => ' fa-try',
					'fa-tty' => ' fa-tty',
					'fa-tumblr' => ' fa-tumblr',
					'fa-tumblr-square' => ' fa-tumblr-square',
					'fa-twitch' => ' fa-twitch',
					'fa-twitter' => ' fa-twitter',
					'fa-twitter-square' => ' fa-twitter-square',
					'fa-umbrella' => ' fa-umbrella',
					'fa-underline' => ' fa-underline',
					'fa-undo' => ' fa-undo',
					'fa-university' => ' fa-university',
					'fa-unlock' => ' fa-unlock',
					'fa-unlock-alt' => ' fa-unlock-alt',
					'fa-upload' => ' fa-upload',
					'fa-usd' => ' fa-usd',
					'fa-user' => ' fa-user',
					'fa-user-md' => ' fa-user-md',
					'fa-user-plus' => ' fa-user-plus',
					'fa-user-secret' => ' fa-user-secret',
					'fa-user-times' => ' fa-user-times',
					'fa-users' => ' fa-users',
					'fa-venus' => ' fa-venus',
					'fa-venus-double' => ' fa-venus-double',
					'fa-venus-mars' => ' fa-venus-mars',
					'fa-viacoin' => ' fa-viacoin',
					'fa-video-camera' => ' fa-video-camera',
					'fa-vimeo' => ' fa-vimeo',
					'fa-vimeo-square' => ' fa-vimeo-square',
					'fa-vine' => ' fa-vine',
					'fa-vk' => ' fa-vk',
					'fa-volume-down' => ' fa-volume-down',
					'fa-volume-off' => ' fa-volume-off',
					'fa-volume-up' => ' fa-volume-up',
					'fa-weibo' => ' fa-weibo',
					'fa-weixin' => ' fa-weixin',
					'fa-whatsapp' => ' fa-whatsapp',
					'fa-wheelchair' => ' fa-wheelchair',
					'fa-wifi' => ' fa-wifi',
					'fa-wikipedia-w' => ' fa-wikipedia-w',
					'fa-windows' => ' fa-windows',
					'fa-wordpress' => ' fa-wordpress',
					'fa-wrench' => ' fa-wrench',
					'fa-xing' => ' fa-xing',
					'fa-xing-square' => ' fa-xing-square',
					'fa-y-combinator' => ' fa-y-combinator',
					'fa-yahoo' => ' fa-yahoo',
					'fa-yelp' => ' fa-yelp',
					'fa-youtube' => ' fa-youtube',
					'fa-youtube-play' => ' fa-youtube-play',
					'fa-youtube-square' => ' fa-youtube-square',
				),
			),
			array (
				'key' => 'field_560237b0ae15c',
				'label' => 'Bild',
				'name' => 'plug-image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5602367dae159',
							'operator' => '!=',
							'value' => 'none',
						),
						array (
							'field' => 'field_56023703ae15a',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56023819ae15f',
				'label' => 'Utseende',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56023823ae160',
				'label' => 'Storlek',
				'name' => 'plug-size',
				'type' => 'radio',
				'choices' => array (
					3 => 'Standard (25%)',
					4 => 'Medium (33%)',
					6 => 'Störst (50%)',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 3,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_560238baae161',
				'label' => 'Bakgrundsfärg',
				'name' => 'plug-background-color',
				'type' => 'select',
				'choices' => array (
					'white-bg' => 'Vit',
					'black-bg' => 'Svart',
					'grey-bg' => 'Ljusgrå',
					'grey-bg darken' => 'Grå',
					'grey-bg darken-3' => 'Mörkgrå',
					'blue-bg' => 'Blå',
					'blue-bg darken' => 'Mörkblå',
					'yellow-bg' => 'Gul',
				),
				'default_value' => 'white-bg',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023981ae162',
				'label' => 'Textfärg',
				'name' => 'plug-text-color',
				'type' => 'select',
				'choices' => array (
					'white-text' => 'Vit',
					'black-text' => 'Svart',
					'grey-text' => 'Mörkgrå',
					'blue-text' => 'Blå',
				),
				'default_value' => 'black-text',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_560239d1ae163',
				'label' => 'Kantfärg',
				'name' => 'plug-border-color',
				'type' => 'select',
				'choices' => array (
					'border-bottom-none' => 'Ingen',
					'border-bottom-white' => 'Vit',
					'border-bottom-black' => 'Svart',
					'border-bottom-grey' => 'Grå',
					'border-bottom-dk-grey' => 'Mörkgrå',
					'border-bottom-blue' => 'Blå',
					'border-bottom-dk-blue' => 'Mörkblå',
					'border-bottom-yellow' => 'Gul',
				),
				'default_value' => 'border-bottom-none',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023a47ae164',
				'label' => 'Länkning',
				'name' => '',
				'type' => 'tab',
				'instructions' => 'internal : Länka till lokal sida
	external : Länka till extern URL
	file : Länka till fil eller media',
			),
			array (
				'key' => 'field_56023a9d94539',
				'label' => 'Länktyp',
				'name' => 'plug-link-type',
				'type' => 'select',
				'choices' => array (
					'internal' => 'Länka till lokal sida',
					'external' => 'Länka till extern URL',
					'file' => 'Länka till fil eller media',
				),
				'default_value' => 'internal',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023aac9453a',
				'label' => 'Sidlänk',
				'name' => 'plug-link-page',
				'type' => 'page_link',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56023a9d94539',
							'operator' => '==',
							'value' => 'internal',
						),
					),
					'allorany' => 'all',
				),
				'post_type' => array (
					0 => 'page',
					1 => 'offer',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56023ad89453b',
				'label' => 'URL',
				'name' => 'plug-link-url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56023a9d94539',
							'operator' => '==',
							'value' => 'external',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56023aef9453c',
				'label' => 'Fil',
				'name' => 'plug-link-file',
				'type' => 'file',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56023a9d94539',
							'operator' => '==',
							'value' => 'file',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'library' => 'all',
			),
			array (
				'key' => 'field_56023b149453d',
				'label' => 'Länkmål',
				'name' => 'plug-link-target',
				'type' => 'select',
				'choices' => array (
					'_self' => 'Öppna i samma fönster',
					'_blank' => 'Öppna i nytt fönster',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'plug',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sidans-installningar',
		'title' => 'Sidans inställningar',
		'fields' => array (
			array (
				'key' => 'field_56025608cabdd',
				'label' => 'Sidomeny',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5602562fcabde',
				'label' => 'Visa i sidomenyn',
				'name' => 'sidebar',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5602567bcabdf',
						'label' => 'Innehåll',
						'name' => 'sidebar-content',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'menu' => 'Sidans meny',
							'plugs' => 'Puffar',
							'custom' => 'Eget innehåll',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_560256b8cabe0',
						'label' => 'Puffar',
						'name' => 'sidebar-plugs',
						'type' => 'relationship',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5602567bcabdf',
									'operator' => '==',
									'value' => 'plugs',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'return_format' => 'object',
						'post_type' => array (
							0 => 'plug',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'filters' => array (
							0 => 'search',
						),
						'result_elements' => array (
							0 => 'post_title',
						),
						'max' => '',
					),
					array (
						'key' => 'field_560256d3cabe1',
						'label' => 'Eget innehåll',
						'name' => 'sidebar-custom',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5602567bcabdf',
									'operator' => '==',
									'value' => 'custom',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_56025bc6f5b68',
						'label' => 'Bakgrundsfärg',
						'name' => 'sidebar-background-color',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5602567bcabdf',
									'operator' => '==',
									'value' => 'custom',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'transparent-bg' => 'Ingen',
							'white-bg' => 'Vit',
							'black-bg' => 'Svart',
							'grey-bg' => 'Ljusgrå',
							'grey-bg darken' => 'Grå',
							'grey-bg darken-3' => 'Mörkgrå',
							'blue-bg' => 'Blå',
							'blue-bg darken' => 'Mörkblå',
							'yellow-bg' => 'Gul',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_560261ebf5b69',
						'label' => 'Kantfärg',
						'name' => 'sidebar-border-color',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5602567bcabdf',
									'operator' => '==',
									'value' => 'custom',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'border-bottom-none' => 'Ingen',
							'border-bottom-white' => 'Vit',
							'border-bottom-black' => 'Svart',
							'border-bottom-grey' => 'Grå',
							'border-bottom-dk-grey' => 'Mörkgrå',
							'border-bottom-blue' => 'Blå',
							'border-bottom-dk-blue' => 'Mörkblå',
							'border-bottom-yellow' => 'Gul',
						),
						'default_value' => 'border-bottom-none',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till innehåll',
			),
			array (
				'key' => 'field_560256edcabe2',
				'label' => 'SEO',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_560256fccabe3',
				'label' => 'Title',
				'name' => 'seo-title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5602570ecabe4',
				'label' => 'Keywords',
				'name' => 'seo-keywords',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5602571ecabe5',
				'label' => 'Description',
				'name' => 'seo-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_startsida',
		'title' => 'Startsida',
		'fields' => array (
			array (
				'key' => 'field_560229cdb62d9',
				'label' => 'Bildspel',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56022a1eb62da',
				'label' => 'Bilder',
				'name' => 'slideshow-slides',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_56022a77b62db',
						'label' => 'Bild',
						'name' => 'slideshow-slide-image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_56022ab7b62dc',
						'label' => 'Länktyp',
						'name' => 'slideshow-slide-linktype',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'internal' => 'Länka till lokal sida',
							'external' => 'Länka till extern URL',
							'file' => 'Länka till fil eller media',
						),
						'default_value' => 'internal',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_56022afab62dd',
						'label' => 'Sida',
						'name' => 'slideshow-slide-pagelink',
						'type' => 'page_link',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_56022ab7b62dc',
									'operator' => '==',
									'value' => 'internal',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'post_type' => array (
							0 => 'page',
							1 => 'offer',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_56022b19b62de',
						'label' => 'URL',
						'name' => 'slideshow-slide-url',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_56022ab7b62dc',
									'operator' => '==',
									'value' => 'external',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56022b2fb62df',
						'label' => 'Fil',
						'name' => 'slideshow-slide-file',
						'type' => 'file',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_56022ab7b62dc',
									'operator' => '==',
									'value' => 'file',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_56022b47b62e0',
						'label' => 'Länkmål',
						'name' => 'slideshow-slide-target',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'_self' => 'Öppna i samma fönster',
							'_blank' => 'Öppna i nytt fönster',
						),
						'default_value' => '_self',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till bild',
			),
			array (
				'key' => 'field_56022b69b62e1',
				'label' => 'Innehåll',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_56023fce56ed6',
				'label' => 'Rader',
				'name' => 'frontpage-row',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_56023ff456ed7',
						'label' => 'Innehåll',
						'name' => 'row-content',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'custom' => 'Eget innehåll',
							'plugs' => 'Puffar',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_5602404056ed8',
						'label' => 'Eget innehåll',
						'name' => 'row-content-custom',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_56023ff456ed7',
									'operator' => '==',
									'value' => 'custom',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_5602406456ed9',
						'label' => 'Puffar',
						'name' => 'row-content-plugs',
						'type' => 'relationship',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_56023ff456ed7',
									'operator' => '==',
									'value' => 'plugs',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'return_format' => 'object',
						'post_type' => array (
							0 => 'plug',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'filters' => array (
							0 => 'search',
						),
						'result_elements' => array (
							0 => 'post_title',
						),
						'max' => '',
					),
					array (
						'key' => 'field_5602408f56eda',
						'label' => 'Bakgrundsfärg',
						'name' => 'row-content-background',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'transparent' => 'Ingen',
							'white-bg' => 'Vit',
							'black-bg' => 'Svart',
							'grey-bg' => 'Ljusgrå',
							'grey-bg.darken' => 'Grå',
							'grey-bg.darken-3' => 'Mörkgrå',
							'blue-bg' => 'Blå',
							'blue-bg.darken' => 'Mörkblå',
							'yellow-bg' => 'Gul',
						),
						'default_value' => 'transparent',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till rad',
			),
			array (
				'key' => 'field_56022ba1b62e3',
				'label' => 'Bilar i lager',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5602333c5cec9',
				'label' => 'Rubrik',
				'name' => 'assortment-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_560233585ceca',
				'label' => 'Fordonsurval',
				'name' => 'assortment-choice',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'assortment',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-startsida',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_blogg-och-inlagg',
		'title' => 'Blogg och inlägg',
		'fields' => array (
			array (
				'key' => 'field_560545c932335',
				'label' => 'Antal per sida',
				'name' => 'blog-page-size',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_56054b175a6e2',
				'label' => 'Från år',
				'name' => 'blog-from-year',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'blog-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


?>