
<?php
/*
Plugin Name: BytBil Innehållsblock
Description: Gör det möjligt att använda sig av innehållsblock i BytBil CMS 2.0
Author: Sebastian Jonsson / Leo Starcevic : BytBil.com
Version: 2.0
Author URI: http://www.bytbil.com
*/

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_innehall',
        'title' => 'Innehåll',
        'fields' => array (
            array(
                'key' => 'field_5244b23b3e152',
                'label' => 'Innehåll',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5565d681313c5',
                'label' => 'Innehåll',
                'name' => 'content',
                'type' => 'flexible_content',
                'layouts' => array (
                    array (
                        'label' => 'Anläggningar',
                        'name' => 'content-facility',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537111553987',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9zue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537111553987',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537dfd096778',
                                'label' => 'Anläggningar',
                                'name' => 'facility',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array (
                                    0 => 'facility',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'filters' => array (
                                    0 => 'search',
                                ),
                                'result_elements' => array (
                                    0 => 'post_title',
                                ),
                                'max' => 1,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Bildspel',
                        'name' => 'content-slideshow',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537df5811293',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9xue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537df5811293',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537e13443265',
                                'label' => 'Bildspel',
                                'name' => 'slideshow',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'slideshow',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Eget innehåll',
                        'name' => 'content-custom',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537df5703710',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9cue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537df5703710',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537dnnn1481e',
                                'label' => 'Innehåll',
                                'name' => 'wysiwyg',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Erbjudande',
                        'name' => 'content-offer',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537111338638',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9vue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537111338638',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_931094u1jurq',
                                'label' => 'Lista alla erbjudanden',
                                'name' => 'all-offers',
                                'type' => 'true_false',
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_5537e13999865',
                                'label' => 'Erbjudande',
                                'name' => 'offer',
                                'type' => 'post_object',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_931094u1jurq',
                                            'operator' => '!=',
                                            'value' => '1',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'offer',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Fordon i lager',
                        'name' => 'content-assortment',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13558638',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9bue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537e13558638',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537e13555638',
                                'label' => 'Rubrik',
                                'name' => 'assortment-header',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                                'instructions' => 'Fyll i en rubrik som du vill visa ovanför fordonsurvalet'
                            ),
                            array (
                                'key' => 'field_5537e187638',
                                'label' => 'Visa länk till alla lagerbilar',
                                'name' => 'assortment-link',
                                'type' => 'radio',
                                'choices' => array (
                                    'false' => 'Nej',
                                    'true' => 'Ja',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'false',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13558639',
                                'label' => 'Fordonsurval',
                                'name' => 'assortment',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'assortment',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Formulär',
                        'name' => 'content-form',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810dua8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13113438',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9nue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537e13113438',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_556c1c4bbe3ea',
                                'label' => 'Formulär',
                                'name' => 'form',
                                'type' => 'post_object',
                                'post_type' => array (
                                    0 => 'wpcf7_contact_form',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Iframe',
                        'name' => 'content-iframe',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810dup8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13128078',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eu09l0e',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537e13128078',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_556ede5a273e4',
                                'label' => 'Titel',
                                'name' => 'iframe-title',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_556ede28273e2',
                                'label' => 'Adress',
                                'name' => 'iframe-url',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_556ede4b273e3',
                                'label' => 'Höjd',
                                'name' => 'iframe-height',
                                'type' => 'text',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Nybilsmodeller',
                        'name' => 'content-newcarmodel',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810dua8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13128028',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9l0e',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537e13128028',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537e13558100',
                                'label' => 'Nybilsmodellista',
                                'name' => 'newcarmodel_list',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'newcarmodel_list',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Personal',
                        'name' => 'content-employee',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537e13123438',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9mue',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537e13123438',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_541fab9e566c7',
                                'label' => 'Vilken personal?',
                                'name' => 'employees',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'single' => 'Enskild personal',
                                    'multiple' => 'Personallista',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 0,
                                'layout' => 'vertical',
                            ),
                            array (
                                'key' => 'field_5537e19022639',
                                'label' => 'Personal',
                                'name' => 'employee',
                                'type' => 'post_object',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_541fab9e566c7',
                                            'operator' => '==',
                                            'value' => 'single',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'post_type' => array (
                                    0 => 'employee',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_541c25ba4cee7',
                                'label' => 'Dölj personallistans rubrik',
                                'name' => 'employee-hide-header',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_541fab9e566c7',
                                            'operator' => '==',
                                            'value' => 'multiple',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array(
                                'key' => 'field_541c25ba4ca54',
                                'label' => 'Antal per rad',
                                'name' => 'employee-cols',
                                'type' => 'select',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_541fab9e566c7',
                                            'operator' => '==',
                                            'value' => 'multiple',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'choices' => array(
                                    '6' => 'Två',
                                    '4' => 'Tre',
                                    '3' => 'Fyra',
                                ),
                                'message' => '',
                                'default_value' => '4',
                            ),
                            array(
                                'key' => 'field_541c25b566ec8',
                                'label' => 'Personallistor',
                                'name' => 'employee-lists',
                                'type' => 'relationship',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_541fab9e566c7',
                                            'operator' => '==',
                                            'value' => 'multiple',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'employee_list',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Puffar',
                        'name' => 'content-plugs',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_553790810due8',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'background-color',
                                'type' => 'color_picker',
                                'description' => 'Bakgrundsfärgen på innehållet',
                                'column_width' => '',
                                'default_value' => 'transparent',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5537dfc914823',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array (
                                    12 => '100%',
                                    9 => '75%',
                                    8 => '66%',
                                    6 => '50%',
                                    4 => '33%',
                                    3 => '25%',
                                    2 => '16%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 12,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_addj290j9eui9que',
                                'label' => 'Full bredd',
                                'name' => 'full-width',
                                'type' => 'true_false',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_5537dfc914823',
                                            'operator' => '==',
                                            'value' => 12,
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array (
                                'key' => 'field_5537dfd014825',
                                'label' => 'Puffar',
                                'name' => 'content-plugs',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array (
                                    0 => 'plug',
                                ),
                                'taxonomy' => array (
                                    0 => 'all',
                                ),
                                'filters' => array (
                                    0 => 'search',
                                ),
                                'result_elements' => array (
                                    0 => 'post_title',
                                ),
                                'max' => 4,
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Lägg till',
                'min' => '',
                'max' => '',
            ),
            array(
                'key' => 'field_5244b23b3e062',
                'label' => 'SEO',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_5244b85105ba1',
                'label' => 'Titeltag',
                'name' => 'pagesettings-title-tag',
                'type' => 'text',
                'instructions' => 'Skriv över sidans standard Titel-tag.',
                'default_value' => '',
                'placeholder' => 'Exempel: Mazda återförsäljare - Mesta bilhandlaren i Stockholm!',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5244b8c105ba2',
                'label' => 'META Description',
                'name' => 'pagesettings-meta-description',
                'type' => 'textarea',
                'instructions' => 'Fyll i en egen description för webbsidan.',
                'default_value' => '',
                'placeholder' => 'Exempel: Stockholms främsta bilhandlare - Nya Mazda.',
                'maxlength' => 160,
                'rows' => 3,
                'formatting' => 'none',
            ),
            array(
                'key' => 'field_5244b93305ba3',
                'label' => 'META Keywords',
                'name' => 'pagesettings-meta-keywords',
                'type' => 'text',
                'instructions' => 'Fyll i ett antal relevanta keywords som beskriver er hemsida. Separera med kommatecken (,).',
                'default_value' => '',
                'placeholder' => 'Exempel: (Nya bilar, Stockholm, Mazda)',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}

?>

