<?php
// Add the settings menu
if (function_exists('acf_set_options_page_title')) {
    acf_set_options_page_title('Siteinställningar');
    acf_add_options_sub_page('Globala Inställningar');
    acf_add_options_sub_page('Footer');
    if (current_user_can('manage_options')) {
        acf_add_options_sub_page('Avancerat');
    }
}

// Add custom fields to settings menu
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_footer',
        'title' => 'Footer',
        'fields' => array(
            array(
                'key' => 'field_5318752faf19b',
                'label' => 'Footerbild Natt',
                'name' => 'footerbild_natt',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_52f38a71226a9',
                'label' => 'Footerbild Dag',
                'name' => 'footerbild_dag',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_5318752faf12c',
                'label' => 'Dagbild Start',
                'name' => 'dagbildstart',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5318752faf11a',
                'label' => 'Dagbild Slut',
                'name' => 'dagbildslut',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52e57082227f8',
                'label' => 'Footertext',
                'name' => 'footertext',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_53147096ae6b9',
                'label' => 'Footertext 2',
                'name' => 'footertextafter',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-footer',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_globala-installningar',
        'title' => 'Globala inställningar',
        'fields' => array(
            array(
                'key' => 'field_52e63b592cce3',
                'label' => 'Sociala länkar',
                'name' => 'social_links',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52e63b952cce5',
                        'label' => 'Ikon',
                        'name' => 'type',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52e63b7b2cce4',
                        'label' => 'URL',
                        'name' => 'url',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Lägg till social media',
            ),
            array(
                'key' => 'field_52e643645c08e',
                'label' => 'Sociala länkar-plugg',
                'name' => 'social_links_plug',
                'type' => 'repeater',
                'instructions' => 'Rutan som visas till höger om länkarna till sociala medier.',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52e643fef4bd7',
                        'label' => 'Rubrik',
                        'name' => 'header',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52e64409f4bd8',
                        'label' => 'Brödtext',
                        'name' => 'bread',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => 1,
                'layout' => 'table',
                'button_label' => '',
            ),
            array(
                'key' => 'field_52e6472d02c79',
                'label' => 'Mittpluggikoner',
                'name' => 'middle_plug_icons',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52f8f6a2ba743',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f83aba746',
                        'label' => 'Länktyp',
                        'name' => 'lanktyp',
                        'type' => 'radio',
                        'choices' => array(
                            'Extern Länk' => 'Extern Länk',
                            'Intern Länk' => 'Intern Länk',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f6faba744',
                        'label' => 'Intern Länk',
                        'name' => 'Internlänk',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Intern Länk',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52f8f9110e76e',
                        'label' => 'Extern Länk',
                        'name' => 'Externlank',
                        'type' => 'text',
                        'required' => 1,
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Extern Länk',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52e6479a68fb9',
                        'label' => 'Ikonbild',
                        'name' => 'icon_image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52e647cd68fba',
                        'label' => 'Ikontext',
                        'name' => 'title_text',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => 4,
                'layout' => 'row',
                'button_label' => 'Lägg Till Mittplugg',
            ),
            array(
                'key' => 'field_52e64ba17e5a6',
                'label' => 'Bilmärkespluggar',
                'name' => 'brand_plugs',
                'type' => 'repeater',
                'instructions' => 'De bilmärkespluggar som visas under slidern på startsidan.',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52e64bcb7e5a7',
                        'label' => 'Märke',
                        'name' => 'marke',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52e64bcb7e5a9',
                        'label' => 'Märke Svartvit',
                        'name' => 'marke-bw',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52f8f6a2ba743',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f83aba746',
                        'label' => 'Länktyp',
                        'name' => 'lanktyp',
                        'type' => 'radio',
                        'choices' => array(
                            'Extern Länk' => 'Extern Länk',
                            'Intern Länk' => 'Intern Länk',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f6faba744',
                        'label' => 'Intern Länk',
                        'name' => 'internlank',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Intern Länk',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52f8f9110e76e',
                        'label' => 'Extern Länk',
                        'name' => 'externlank',
                        'type' => 'text',
                        'required' => 1,
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Extern Länk',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg Till Märke',
            ),
            array(
                'key' => 'field_52f88c5b549d1',
                'label' => 'Bilmärkespluggar Footer',
                'name' => 'brand_plugs_footer',
                'type' => 'repeater',
                'instructions' => 'De bilmärkespluggar som visas i footern på alla sidor',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52f88c82549d2',
                        'label' => 'Marke',
                        'name' => 'marke',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52f8f6a2ba743',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f83aba746',
                        'label' => 'Länktyp',
                        'name' => 'lanktyp',
                        'type' => 'radio',
                        'choices' => array(
                            'Extern Länk' => 'Extern Länk',
                            'Intern Länk' => 'Intern Länk',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f8f6faba744',
                        'label' => 'Intern Länk',
                        'name' => 'internlank',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Intern Länk',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52f8f9110e76e',
                        'label' => 'Extern Länk',
                        'name' => 'externlank',
                        'type' => 'text',
                        'required' => 1,
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f8f83aba746',
                                    'operator' => '==',
                                    'value' => 'Extern Länk',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg Till Märke',
            ),
            array(
                'key' => 'field_52e79997aa748',
                'label' => 'Öppettider',
                'name' => 'opentimes',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52e94ca8362bf',
                        'label' => 'Fritext',
                        'name' => 'fritext',
                        'type' => 'text',
                        'instructions' => 'Till exempel vilken avdelning. Eller vilken ort. Eller bägge.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_531dd46a96d36',
                        'label' => 'Kategori',
                        'name' => 'kategorin',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52e94cd4362c0',
                        'label' => 'Tider',
                        'name' => 'times',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_52e94cec362c1',
                                'label' => 'Dag(ar)',
                                'name' => 'day',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_52e94cff362c2',
                                'label' => 'Tider',
                                'name' => 'time',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'table',
                        'button_label' => 'Lägg till tid',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-globala-installningar',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_undersidaheader',
        'title' => 'Header',
        'fields' => array(
            array(
                'key' => 'field_52e575d0a29b3',
                'label' => 'Genvägslänkar',
                'name' => 'shortcuts',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_537c3021b4339',
                        'label' => 'Länktyp',
                        'name' => 'link-type',
                        'type' => 'radio',
                        'column_width' => 10,
                        'choices' => array(
                            'internal' => 'Intern',
                            'external' => 'Extern',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_52e575e4a29b4',
                        'label' => 'Text',
                        'name' => 'text',
                        'type' => 'text',
                        'column_width' => 25,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52e575f1a29b5',
                        'label' => 'Länk',
                        'name' => 'pagelink',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_537c3021b4339',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => 30,
                        'post_type' => array(
                            0 => 'post',
                            1 => 'page',
                            2 => 'puff',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_537c3062b433b',
                        'label' => 'URL',
                        'name' => 'link-url',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_537c3021b4339',
                                    'operator' => '==',
                                    'value' => 'external',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => 30,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Lägg till länk',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_avancerat',
        'title' => 'Avancerat',
        'fields' => array(
            array(
                'key' => 'field_52e536fb0dcfe',
                'label' => 'FilterId',
                'name' => 'filterid',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52e53eebfbacc',
                'label' => 'Söksida',
                'name' => 'soksida',
                'type' => 'page_link',
                'instructions' => 'Sida där sökresultat skall visas (Sidmall: Listvy)',
                'post_type' => array(
                    0 => 'page',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-avancerat',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_accesspaket',
        'title' => 'Accesspaket',
        'fields' => array(
            array(
                'key' => 'field_52de5a771875e',
                'label' => 'Kontaktformulär',
                'name' => 'kontaktformular',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '152',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
                0 => 'excerpt',
                1 => 'custom_fields',
                2 => 'discussion',
                3 => 'comments',
                4 => 'revisions',
                5 => 'author',
                6 => 'format',
                7 => 'featured_image',
                8 => 'categories',
                9 => 'tags',
                10 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_bygg-bil',
        'title' => 'Bygg bil',
        'fields' => array(
            array(
                'key' => 'field_52de8534df929',
                'label' => 'Länkar',
                'name' => 'links',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52de8573df92a',
                        'label' => 'Text',
                        'name' => 'text',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52de8581df92b',
                        'label' => 'Url',
                        'name' => 'url',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52fa04f92e017',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '_blank',
                        'layout' => 'vertical',
                    ),
                ),
                'row_min' => '',
                'row_limit' => 3,
                'layout' => 'row',
                'button_label' => 'Lägg till rad',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'bygg_bil',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_headerbildspelet',
        'title' => 'headerbildspelet',
        'fields' => array(
            array(
                'key' => 'field_52f1f663d710e',
                'label' => 'Header Bildspel',
                'name' => 'headerbildspel',
                'type' => 'text',
                'required' => 0,
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_puffar',
        'title' => 'Puffar',
        'fields' => array(
            array(
                'key' => 'field_52dc2e99791bc',
                'label' => 'Bild',
                'name' => 'bild',
                'type' => 'image',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_534a51a323ff7',
                            'operator' => '==',
                            'value' => 'false',
                        ),
                        array(
                            'field' => 'field_52dc2ef0791bf',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_52dc2ef0791bf',
                            'operator' => '==',
                            'value' => '3',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_534a51a323ff7',
                'label' => 'Extra Text-Ruta istället för bild',
                'name' => 'twotext',
                'type' => 'select',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_52dc2ef0791bf',
                            'operator' => '==',
                            'value' => '4',
                        ),

                    ),
                    'allorany' => 'all',
                ),
                'choices' => array(
                    'true' => 'Ja',
                    'false' => 'Nej',
                ),
                'default_value' => 'false',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_52dc2eb6791bd',
                'label' => 'Ingress',
                'name' => 'ingress',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'no',
            ),
            array(
                'key' => 'field_534a51ae23ff8',
                'label' => 'Ingress Nummer 2',
                'name' => 'ingress2',
                'type' => 'select',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_534a51a323ff7',
                            'operator' => '==',
                            'value' => 'true',
                        ),
                        array(
                            'field' => 'field_52dc2ef0791bf',
                            'operator' => '==',
                            'value' => '4',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'no',
            ),
            array(
                'key' => 'field_52dc2ef0791bf',
                'label' => 'Storlek',
                'name' => 'storlek',
                'type' => 'select',
                'required' => 1,
                'choices' => array(
                    1 => 'Liten',
                    3 => 'Medel',
                    4 => 'Stor',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_52dc2fa962189',
                'label' => 'Bildjustering',
                'name' => 'bildjustering',
                'type' => 'select',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_52dc2ef0791bf',
                            'operator' => '==',
                            'value' => '4',
                        ),
                        array(
                            'field' => 'field_534a51a323ff7',
                            'operator' => '==',
                            'value' => 'false',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array(
                    'image-left' => 'Vänster',
                    'image-right' => 'Höger',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_52fa04f92e006',
                'label' => 'Öppna Länk i',
                'name' => 'open_link_in',
                'type' => 'radio',
                'choices' => array(
                    '_self' => 'Öppna i samma Fönster',
                    '_blank' => 'Öppna i eget Fönster',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'puff',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'author',
                7 => 'format',
                8 => 'featured_image',
                9 => 'categories',
                10 => 'tags',
                11 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_undersida',
        'title' => 'Undersida',
        'fields' => array(
            array(
                'key' => 'field_52de6713e32a7',
                'label' => 'Sidokolumn',
                'name' => 'sidokolumn',
                'type' => 'wysiwyg',
                'instructions' => 'Vad som syns i sidokolumnen när man är inne på en undersida',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
            array(
                'key' => 'field_134a527dd7e46',
                'label' => 'Puffar Sidokolumn',
                'name' => 'puffarsidebar',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_12dc2e99791bc',
                        'label' => 'Bild',
                        'name' => 'bild',
                        'type' => 'image',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_134a51cc23ffd',
                        'label' => 'Rubrik',
                        'name' => 'rubrik',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_12dc2eb6791bd',
                        'label' => 'Ingress',
                        'name' => 'ingress',
                        'type' => 'wysiwyg',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'no',
                    ),
                    array(
                        'key' => 'field_12fa04f92e006',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_12f2337b811fd',
                        'label' => 'Länk',
                        'name' => 'pufflank',
                        'type' => 'select',
                        'choices' => array(
                            'ext' => 'Extern länk',
                            'int' => 'Intern länk',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_12f23417811fe',
                        'label' => 'Extern länk',
                        'name' => 'extlink',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_12f2337b811fd',
                                    'operator' => '==',
                                    'value' => 'ext',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_12f23428811ff',
                        'label' => 'Intern länk',
                        'name' => 'intlink',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_12f2337b811fd',
                                    'operator' => '==',
                                    'value' => 'int',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till puff',
            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-undersida.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_puffar-2',
        'title' => 'Puffar',
        'fields' => array(
            array(
                'key' => 'field_52f2337b811fd',
                'label' => 'Länk',
                'name' => 'pufflank',
                'type' => 'select',
                'choices' => array(
                    'ext' => 'Extern länk',
                    'int' => 'Intern länk',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_52f23417811fe',
                'label' => 'Extern länk',
                'name' => 'extlink',
                'type' => 'text',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_52f2337b811fd',
                            'operator' => '==',
                            'value' => 'ext',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f23428811ff',
                'label' => 'Intern länk',
                'name' => 'intlink',
                'type' => 'page_link',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_52f2337b811fd',
                            'operator' => '==',
                            'value' => 'int',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'post_type' => array(
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'puff',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array(
        'id' => 'acf_socialblock',
        'title' => 'socialblock',
        'fields' => array(
            array(
                'key' => 'field_531d77be329d9',
                'label' => 'Social Block',
                'name' => 'social-block',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_531d7807329da',
                        'label' => 'Rubrik',
                        'name' => 'rubrik',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_531d7857329db',
                        'label' => 'Fält',
                        'name' => 'falt',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Lägg till Socialblock',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'sociala-medier.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_svartknapp',
        'title' => 'svartknapp',
        'fields' => array(
            array(
                'key' => 'field_531ed6cfac582',
                'label' => 'Svarta Knappar',
                'name' => 'black-buttons',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_531ed6deac583',
                        'label' => 'Knapptext',
                        'name' => 'knapptext',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52f8f6a2ba743',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_531f23d6a7765',
                        'label' => 'Länktyp',
                        'name' => 'lanktypen',
                        'type' => 'radio',
                        'choices' => array(
                            'ext' => 'Extern länk',
                            'int' => 'Intern länk',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_531f23dca7766',
                        'label' => 'Intern Länk',
                        'name' => 'internlank',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_531f23d6a7765',
                                    'operator' => '==',
                                    'value' => 'int',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_531f23e8a7767',
                        'label' => 'Extern Länk',
                        'name' => 'externlank',
                        'type' => 'text',
                        'required' => 1,
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_531f23d6a7765',
                                    'operator' => '==',
                                    'value' => 'ext',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till knapp',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-accesspaket.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_alternativ-rubrik',
        'title' => 'Alternativ Rubrik',
        'fields' => array(
            array(
                'key' => 'field_531f153e35a0c',
                'label' => 'Alternativ Rubrik',
                'name' => 'alternativ_rubrik',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_538471567a68e',
                'label' => 'Dölj rubriker',
                'name' => 'dolj_rubriker',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'blogg',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
        ),
        'options' => array(
            'position' => 'acf_after_title',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));


    /*  Puffar persidspec  */


    register_field_group(array(
        'id' => 'acf_puffarsidpec',
        'title' => 'Puffarsidpec',
        'fields' => array(
            array(
                'key' => 'field_534a527dd7e46',
                'label' => 'puffarsida',
                'name' => 'puffarsida',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52dc2e99791bc',
                        'label' => 'Bild',
                        'name' => 'bild',
                        'type' => 'image',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_534a51a323ff7',
                                    'operator' => '==',
                                    'value' => 'false',
                                ),
                                array(
                                    'field' => 'field_52dc2ef0791bf',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                                array(
                                    'field' => 'field_52dc2ef0791bf',
                                    'operator' => '==',
                                    'value' => '3',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_534a51a323ff7',
                        'label' => 'Extra Text-Ruta istället för bild',
                        'name' => 'twotext',
                        'type' => 'select',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52dc2ef0791bf',
                                    'operator' => '==',
                                    'value' => '4',
                                ),

                            ),
                            'allorany' => 'all',
                        ),
                        'choices' => array(
                            'true' => 'Ja',
                            'false' => 'Nej',
                        ),
                        'default_value' => 'false',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_534a51cc23ffd',
                        'label' => 'Rubrik',
                        'name' => 'rubrik',
                        'type' => 'text',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52dc2eb6791bd',
                        'label' => 'Ingress',
                        'name' => 'ingress',
                        'type' => 'wysiwyg',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'no',
                    ),
                    array(
                        'key' => 'field_534a51ae23ff8',
                        'label' => 'Ingress Nummer 2',
                        'name' => 'ingress2',
                        'type' => 'select',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_534a51a323ff7',
                                    'operator' => '==',
                                    'value' => 'true',
                                ),
                                array(
                                    'field' => 'field_52dc2ef0791bf',
                                    'operator' => '==',
                                    'value' => '4',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'type' => 'wysiwyg',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'no',
                    ),
                    array(
                        'key' => 'field_52dc2ef0791bf',
                        'label' => 'Storlek',
                        'name' => 'storlek',
                        'type' => 'select',
                        'required' => 1,
                        'choices' => array(
                            1 => 'Liten',
                            3 => 'Medel',
                            4 => 'Stor',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52dc2fa962189',
                        'label' => 'Bildjustering',
                        'name' => 'bildjustering',
                        'type' => 'select',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52dc2ef0791bf',
                                    'operator' => '==',
                                    'value' => '4',
                                ),
                                array(
                                    'field' => 'field_534a51a323ff7',
                                    'operator' => '==',
                                    'value' => 'false',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'choices' => array(
                            'image-left' => 'Vänster',
                            'image-right' => 'Höger',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52fa04f92e006',
                        'label' => 'Öppna Länk i',
                        'name' => 'open_link_in',
                        'type' => 'radio',
                        'choices' => array(
                            '_self' => 'Öppna i samma Fönster',
                            '_blank' => 'Öppna i eget Fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array(
                        'key' => 'field_52f2337b811fd',
                        'label' => 'Länk',
                        'name' => 'pufflank',
                        'type' => 'select',
                        'choices' => array(
                            'ext' => 'Extern länk',
                            'int' => 'Intern länk',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_52f23417811fe',
                        'label' => 'Extern länk',
                        'name' => 'extlink',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f2337b811fd',
                                    'operator' => '==',
                                    'value' => 'ext',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52f23428811ff',
                        'label' => 'Intern länk',
                        'name' => 'intlink',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_52f2337b811fd',
                                    'operator' => '==',
                                    'value' => 'int',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'post_type' => array(
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till puff',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-undersida.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-undersida-nosidebar.php',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-listvy.php',
                    'order_no' => 2,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-listvy-oldcars.php',
                    'order_no' => 3,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-listvy-transport.php',
                    'order_no' => 4,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-listvy-all.php',
                    'order_no' => 5,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'sociala-medier.php',
                    'order_no' => 6,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-accesspaket.php',
                    'order_no' => 7,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page.php',
                    'order_no' => 8,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'index.php',
                    'order_no' => 9,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));


}



?>