<?php
add_action('init', 'cptui_register_my_cpt_af_slideshow');
function cptui_register_my_cpt_af_slideshow()
{
    register_post_type('af_slideshow', array(
        'label' => 'ÅF Bildspel',
        'description' => '',
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => array('slug' => 'af_slideshow', 'with_front' => true),
        'query_var' => true,
        'supports' => array('title', 'revisions'),
        'labels' => array(
            'name' => 'ÅF Bildspel',
            'singular_name' => 'Bildspel',
            'menu_name' => 'ÅF Bildspel',
            'add_new' => 'Add Bildspel',
            'add_new_item' => 'Add New Bildspel',
            'edit' => 'Edit',
            'edit_item' => 'Edit Bildspel',
            'new_item' => 'New Bildspel',
            'view' => 'View Bildspel',
            'view_item' => 'View Bildspel',
            'search_items' => 'Search ÅF Bildspel',
            'not_found' => 'No ÅF Bildspel Found',
            'not_found_in_trash' => 'No ÅF Bildspel Found in Trash',
            'parent' => 'Parent Bildspel',
        )
    ));
}

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_aterforsaljare-bildspel',
        'title' => 'Återförsäljare Bildspel',
        'fields' => array(
            array(
                'key' => 'field_540fdc303543623e',
                'label' => 'Bildspel',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54746e3fb72ff',
                'label' => 'Bilder',
                'name' => 'af-slideshow_images',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_54746e65b7300',
                        'label' => 'Bild',
                        'name' => 'af-slideshow_image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_54746e93b7301',
                        'label' => 'Rubrik',
                        'name' => 'af-slideshow_header',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54746ea8b7302',
                        'label' => 'Text',
                        'name' => 'af-slideshow_text',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'formatting' => 'br',
                    ),
                    array(
                        'key' => 'field_54746ebfb7303',
                        'label' => 'Länkknappar',
                        'name' => 'af-slideshow_link-buttons',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_54746f0ab7304',
                                'label' => 'Länktext',
                                'name' => 'af-slideshow_button-text',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_54746f18b7305',
                                'label' => 'Länka till',
                                'name' => 'af-slideshow_button-link',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'internal' => 'Lokal sida',
                                    'external' => 'Extern URL',
                                    'file' => 'Fil / Dokument'
                                ),
                                'default_value' => 'internal',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                "key" => "field_linktargetslideshowaf8ayshdu0b0",
                                "label" => "Öppna länk i",
                                "name" => "af-slideshow_button-target",
                                "type" => "radio",
                                "choices" => array(
                                    "_self" => "Samma fönster",
                                    "_blank" => "Nytt fönster",
                                    "lightbox" => "Lightbox"
                                ),
                            ),
                            array(
                                'key' => 'field_d5eb7b94-b50e-41e1-97fb-fcd398f20013',
                                'label' => 'File / Dokument',
                                'name' => 'af-slideshow-button-link-file',
                                'type' => 'file',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_54746f18b7305',
                                            'operator' => '==',
                                            'value' => 'file',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                            ),
                            array(
                                'key' => 'field_54746f4db7306',
                                'label' => 'Sida',
                                'name' => 'af-slideshow_button-link-page',
                                'type' => 'post_object',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_54746f18b7305',
                                            'operator' => '==',
                                            'value' => 'internal',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'post_type' => array(
                                    0 => 'page',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_54746f64b7307',
                                'label' => 'Adress',
                                'name' => 'af-slideshow_button-link-url',
                                'type' => 'text',
                                'conditional_logic' => array(
                                    'status' => 1,
                                    'rules' => array(
                                        array(
                                            'field' => 'field_54746f18b7305',
                                            'operator' => '==',
                                            'value' => 'external',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_54746f7cb7308',
                                'label' => 'Länkbeteende',
                                'name' => 'af-slideshow_button-link-target',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    '_self' => 'Öppna i samma fönster',
                                    '_blank' => 'Öppna i nytt fönster',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_54746fb8b7309',
                                'label' => 'Färg',
                                'name' => 'af-slideshow_button-color',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'white' => 'Vit',
                                    'black' => 'Svart',
                                    'gray' => 'Grå',
                                    'blue' => 'Blå',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'row',
                        'button_label' => 'Lägg till knapp',
                    ),
                    array(
                        'key' => 'field_54746ff9b730a',
                        'label' => 'Bakgrundsfärg',
                        'name' => 'af-slideshow_color',
                        'type' => 'select',
                        'column_width' => '',
                        'choices' => array(
                            'white' => 'Vit',
                            'black' => 'Svart',
                            'blue' => 'Blå',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_5474703ab730b',
                        'label' => 'Datumstyrning',
                        'name' => 'af-slideshow_date-control',
                        'type' => 'true_false',
                        'column_width' => '',
                        'message' => '',
                        'default_value' => 0,
                    ),
                    array(
                        'key' => 'field_54747047b730c',
                        'label' => 'Startdatum',
                        'name' => 'af-slideshow_date-start',
                        'type' => 'date_picker',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_5474703ab730b',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'date_format' => 'yymmdd',
                        'display_format' => 'dd/mm/yy',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_54747060b730d',
                        'label' => 'Slutdatum',
                        'name' => 'af-slideshow_date-stop',
                        'type' => 'date_picker',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_5474703ab730b',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'date_format' => 'yymmdd',
                        'display_format' => 'dd/mm/yy',
                        'first_day' => 1,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till bild',
            ),
            array(
                'key' => 'field_540fdc303593e',
                'label' => 'Inställningar',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_540fdcbd3455941',
                'label' => 'Visningstid',
                'name' => 'af-slideshow-settings-duration',
                'type' => 'text',
                'default_value' => '7',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'sekunder',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_540fdc3e3534593f',
                'label' => 'Animation',
                'name' => 'af-slideshow-settings-animation',
                'type' => 'select',
                'choices' => array(
                    'slide' => 'Glid in och ut',
                    'fade' => 'Tona in och ut',
                ),
                'default_value' => 'slide',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_540fdc963594640',
                'label' => 'Animationshastighet',
                'name' => 'af-slideshow-settings-animation-speed',
                'type' => 'text',
                'default_value' => '600',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'millisekunder',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'af_slideshow',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
?>
