<?php

// Register Mercedes-Benz Optionspage
if (function_exists('acf_set_options_page_title')) {
    acf_set_options_page_title('Mercedes-Benz');
    if (is_master()) {
        acf_add_options_sub_page('General-Agent inställningar');
    }
    acf_add_options_sub_page('Återförsäljare inställningar');
}

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_webbplatsinstallningar',
        'title' => 'Webbplatsinställningar',
        'fields' => array(
            array(
                'key' => 'field_5415893aa9950',
                'label' => 'Utseende',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_541588f2a994e',
                'label' => 'Logotyp',
                'name' => 'settings_logotype',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_541589a3a9952',
                'label' => 'Nyheter',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_541589b4a9953',
                'label' => 'Nyheter',
                'name' => 'settings_footer-news',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_541589cda9954',
                        'label' => 'Titel',
                        'name' => 'settings_footer-news-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_541589eaa9955',
                        'label' => 'Länk',
                        'name' => 'settings_footer-news-link',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => 4,
                'layout' => 'row',
                'button_label' => 'Lägg till Nyhet',
            ),
            array(
                'key' => 'field_54158a33a9956',
                'label' => 'Snabblänkar',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54158a3ba9957',
                'label' => 'Snabblänkar',
                'name' => 'settings_footer-links',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_54158a9da9958',
                        'label' => 'Titel',
                        'name' => 'settings_footer-link-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54158ac0a9959',
                        'label' => 'Länktyp',
                        'name' => 'settings_footer-link-type',
                        'type' => 'radio',
                        'column_width' => '',
                        'choices' => array(
                            'internal' => 'Lokal sida',
                            'redirect' => 'Extern sida (omdirigering)',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_54158afca995a',
                        'label' => 'Sidlänk',
                        'name' => 'settings_footer-link-page',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_54158ac0a9959',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_54158b0fa995b',
                        'label' => 'Extern URL',
                        'name' => 'settings_footer-link-url',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_54158ac0a9959',
                                    'operator' => '==',
                                    'value' => 'redirect',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54158b2ba995c',
                        'label' => 'Länkbeteende',
                        'name' => 'settings_footer-link-target',
                        'type' => 'radio',
                        'column_width' => '',
                        'choices' => array(
                            '_self' => 'Öppna i samma fönster',
                            '_blank' => 'Öppna i nytt fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                ),
                'row_min' => '',
                'row_limit' => 5,
                'layout' => 'row',
                'button_label' => 'Lägg till snabblänk',
            ),
            array(
                'key' => 'field_54158b8b92e59',
                'label' => 'Om Webbplatsen',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54158b9e92e5a',
                'label' => 'Om Webbplatsen-länkar',
                'name' => 'settings_about-links',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_54158bb392e5b',
                        'label' => 'Titel',
                        'name' => 'settings_footer-about-link-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54158bee92e5c',
                        'label' => 'Länktyp',
                        'name' => 'settings_footer-about-link-type',
                        'type' => 'radio',
                        'column_width' => '',
                        'choices' => array(
                            'internal' => 'Lokal sida',
                            'redirect' => 'Extern sida (omdirigering)',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_54158c0892e5d',
                        'label' => 'Sidlänk',
                        'name' => 'settings_footer-about-link-page',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_54158bee92e5c',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_54158c2492e5f',
                        'label' => 'Extern URL',
                        'name' => 'settings_footer-about-link-url',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_54158bee92e5c',
                                    'operator' => '==',
                                    'value' => 'redirect',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54158c3d92e60',
                        'label' => 'Länkbeteende',
                        'name' => 'settings_footer-about-link-target',
                        'type' => 'radio',
                        'column_width' => '',
                        'choices' => array(
                            '_self' => 'Öppna i samma fönster',
                            '_blank' => 'Öppna i nytt fönster',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till Om-länk',
            ),
            array(
                'key' => 'field_54158c9192e61',
                'label' => 'Mercedes-Benz.se',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54158c9f92e62',
                'label' => 'Länkar till Mercedes-Benz.se',
                'name' => 'settings_mbse-links',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_54158ce192e63',
                        'label' => 'Titel',
                        'name' => 'settings_mbse-link-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_54158d1592e65',
                        'label' => 'URL på Mercedes-Benz.se',
                        'name' => 'settings_mbse-link-url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till länk',
            ),
            array(
                'key' => 'field_5446179e88927',
                'label' => 'Menyer',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_544617a788928',
                'label' => 'Huvudmeny',
                'name' => 'settings_menu',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_544617c488929',
                        'label' => 'Menyval',
                        'name' => 'settings_menu_item',
                        'type' => 'post_object',
                        'column_width' => '',
                        'post_type' => array(
                            0 => 'page',
                            1 => 'menus',
                        ),
                        'taxonomy' => array(
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till menyval',
            ),

            array(
                "type" => "tab",
                "label" => "Bildspel"
            ),

            array(
                'key' => 'field_540fdcbd345235941',
                'label' => 'Visningstid',
                'name' => 'mb-slideshow-settings-duration',
                'type' => 'text',
                'default_value' => '7',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'sekunder',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_540fdc3e353564593f',
                'label' => 'Animation',
                'name' => 'mb-slideshow-settings-animation',
                'type' => 'select',
                'choices' => array(
                    'slide' => 'Glid in och ut',
                    'fade' => 'Tona in och ut',
                ),
                'default_value' => 'slide',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_540fdc96323594640',
                'label' => 'Animationshastighet',
                'name' => 'mb-slideshow-settings-animation-speed',
                'type' => 'text',
                'default_value' => '600',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'millisekunder',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_544asdrwtwf6179e88927',
                'label' => 'Startsida',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54464118e9a03gaga',
                'label' => 'Snabblänkar',
                'name' => 'ga-frontpage-shortlinks',
                'type' => 'relationship',
                'return_format' => 'object',
                'post_type' => array(
                    0 => 'shortlink',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'filters' => array(
                    0 => 'search',
                ),
                'result_elements' => array(
                    0 => 'post_title',
                ),
                'max' => 8,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-general-agent-installningar',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));

// Registrera ÅF-Inställningar

    register_field_group(array(
        'id' => 'acf_aterforsaljare-installningar',
        'title' => 'Återförsäljare inställningar',
        'fields' => array(
            array(
                'key' => 'field_54339e2992726',
                'label' => 'Generellt',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_5444eb1547294',
                'label' => 'Återförsäljarens namn',
                'name' => 'af-name',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5444eb5b47296',
                'label' => 'Om Återförsäljaren',
                'name' => 'af-about',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_5444eb2647295',
                'label' => 'Återförsäljarens hemsida',
                'name' => 'af-website',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5444ea3147292',
                'label' => 'Försäljning',
                'name' => 'af-reseller',
                'type' => 'checkbox',
                'choices' => array(
                    'pb' => 'Personbilar',
                    'tb' => 'Transportbilar',
                    'lb' => 'Lastbilar',
                    'hb' => 'Hyrbilar',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array(
                'key' => 'field_5448f7ca02fa6',
                'label' => 'BytBil Alias',
                'name' => 'af-bb-alias',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5444ebac47297',
                'label' => 'Utseende',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54339e4092727',
                'label' => 'Logotyp',
                'name' => 'af-logotype',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_54339e5992728',
                'label' => 'Bakgrundsfärg Platta',
                'name' => 'af-logotype-background',
                'type' => 'radio',
                'choices' => array(
                    '#fff' => 'Vit',
                    '#000' => 'Svart',
                    '#00adef' => 'Blå',
                    'profile' => 'Profilfärg',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '#fff',
                'layout' => 'horizontal',
            ),
            array(
                'key' => 'field_54339e9b92729',
                'label' => 'Profilfärg',
                'name' => 'af-profile-color',
                'type' => 'color_picker',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_54339e5992728',
                            'operator' => '==',
                            'value' => 'profile',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array(
                'key' => 'field_5433916100380',
                'label' => 'ÅF-Meny',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_5444fcbd4b557',
                'label' => 'Menyrubrik',
                'name' => 'af-menu-title',
                'type' => 'text',
                'default_value' => 'Mercedes-Benz hos Återförsäljare',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5433917000381',
                'label' => 'Länkar',
                'name' => 'af-menu-links',
                'type' => 'repeater',
                'instructions' => 'Välj dina fem länkar som skall visas i din ÅF-Meny.',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5433919800382',
                        'label' => 'Länknamn',
                        'name' => 'af-menu-link-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_543391d200383',
                        'label' => 'Ikon',
                        'name' => 'af-menu-link-icon',
                        'type' => 'font-awesome',
                        'column_width' => '',
                        'default_value' => 'fa-search',
                        'save_format' => 'class',
                        'allow_null' => 0,
                        'enqueue_fa' => 0,
                        'choices' => array(
                            'fa-adjust' => '? fa-adjust',
                            'fa-adn' => '? fa-adn',
                            'fa-align-center' => '? fa-align-center',
                            'fa-align-justify' => '? fa-align-justify',
                            'fa-align-left' => '? fa-align-left',
                            'fa-align-right' => '? fa-align-right',
                            'fa-ambulance' => '? fa-ambulance',
                            'fa-anchor' => '? fa-anchor',
                            'fa-android' => '? fa-android',
                            'fa-angellist' => '? fa-angellist',
                            'fa-angle-double-down' => '? fa-angle-double-down',
                            'fa-angle-double-left' => '? fa-angle-double-left',
                            'fa-angle-double-right' => '? fa-angle-double-right',
                            'fa-angle-double-up' => '? fa-angle-double-up',
                            'fa-angle-down' => '? fa-angle-down',
                            'fa-angle-left' => '? fa-angle-left',
                            'fa-angle-right' => '? fa-angle-right',
                            'fa-angle-up' => '? fa-angle-up',
                            'fa-apple' => '? fa-apple',
                            'fa-archive' => '? fa-archive',
                            'fa-area-chart' => '? fa-area-chart',
                            'fa-arrow-circle-down' => '? fa-arrow-circle-down',
                            'fa-arrow-circle-left' => '? fa-arrow-circle-left',
                            'fa-arrow-circle-o-down' => '? fa-arrow-circle-o-down',
                            'fa-arrow-circle-o-left' => '? fa-arrow-circle-o-left',
                            'fa-arrow-circle-o-right' => '? fa-arrow-circle-o-right',
                            'fa-arrow-circle-o-up' => '? fa-arrow-circle-o-up',
                            'fa-arrow-circle-right' => '? fa-arrow-circle-right',
                            'fa-arrow-circle-up' => '? fa-arrow-circle-up',
                            'fa-arrow-down' => '? fa-arrow-down',
                            'fa-arrow-left' => '? fa-arrow-left',
                            'fa-arrow-right' => '? fa-arrow-right',
                            'fa-arrow-up' => '? fa-arrow-up',
                            'fa-arrows' => '? fa-arrows',
                            'fa-arrows-alt' => '? fa-arrows-alt',
                            'fa-arrows-h' => '? fa-arrows-h',
                            'fa-arrows-v' => '? fa-arrows-v',
                            'fa-asterisk' => '? fa-asterisk',
                            'fa-at' => '? fa-at',
                            'fa-automobile' => '? fa-automobile',
                            'fa-backward' => '? fa-backward',
                            'fa-ban' => '? fa-ban',
                            'fa-bank' => '? fa-bank',
                            'fa-bar-chart' => '? fa-bar-chart',
                            'fa-bar-chart-o' => '? fa-bar-chart-o',
                            'fa-barcode' => '? fa-barcode',
                            'fa-bars' => '? fa-bars',
                            'fa-beer' => '? fa-beer',
                            'fa-behance' => '? fa-behance',
                            'fa-behance-square' => '? fa-behance-square',
                            'fa-bell' => '? fa-bell',
                            'fa-bell-o' => '? fa-bell-o',
                            'fa-bell-slash' => '? fa-bell-slash',
                            'fa-bell-slash-o' => '? fa-bell-slash-o',
                            'fa-bicycle' => '? fa-bicycle',
                            'fa-binoculars' => '? fa-binoculars',
                            'fa-birthday-cake' => '? fa-birthday-cake',
                            'fa-bitbucket' => '? fa-bitbucket',
                            'fa-bitbucket-square' => '? fa-bitbucket-square',
                            'fa-bitcoin' => '? fa-bitcoin',
                            'fa-bold' => '? fa-bold',
                            'fa-bolt' => '? fa-bolt',
                            'fa-bomb' => '? fa-bomb',
                            'fa-book' => '? fa-book',
                            'fa-bookmark' => '? fa-bookmark',
                            'fa-bookmark-o' => '? fa-bookmark-o',
                            'fa-briefcase' => '? fa-briefcase',
                            'fa-btc' => '? fa-btc',
                            'fa-bug' => '? fa-bug',
                            'fa-building' => '? fa-building',
                            'fa-building-o' => '? fa-building-o',
                            'fa-bullhorn' => '? fa-bullhorn',
                            'fa-bullseye' => '? fa-bullseye',
                            'fa-bus' => '? fa-bus',
                            'fa-cab' => '? fa-cab',
                            'fa-calculator' => '? fa-calculator',
                            'fa-calendar' => '? fa-calendar',
                            'fa-calendar-o' => '? fa-calendar-o',
                            'fa-camera' => '? fa-camera',
                            'fa-camera-retro' => '? fa-camera-retro',
                            'fa-car' => '? fa-car',
                            'fa-caret-down' => '? fa-caret-down',
                            'fa-caret-left' => '? fa-caret-left',
                            'fa-caret-right' => '? fa-caret-right',
                            'fa-caret-square-o-down' => '? fa-caret-square-o-down',
                            'fa-caret-square-o-left' => '? fa-caret-square-o-left',
                            'fa-caret-square-o-right' => '? fa-caret-square-o-right',
                            'fa-caret-square-o-up' => '? fa-caret-square-o-up',
                            'fa-caret-up' => '? fa-caret-up',
                            'fa-cc' => '? fa-cc',
                            'fa-cc-amex' => '? fa-cc-amex',
                            'fa-cc-discover' => '? fa-cc-discover',
                            'fa-cc-mastercard' => '? fa-cc-mastercard',
                            'fa-cc-paypal' => '? fa-cc-paypal',
                            'fa-cc-stripe' => '? fa-cc-stripe',
                            'fa-cc-visa' => '? fa-cc-visa',
                            'fa-certificate' => '? fa-certificate',
                            'fa-chain' => '? fa-chain',
                            'fa-chain-broken' => '? fa-chain-broken',
                            'fa-check' => '? fa-check',
                            'fa-check-circle' => '? fa-check-circle',
                            'fa-check-circle-o' => '? fa-check-circle-o',
                            'fa-check-square' => '? fa-check-square',
                            'fa-check-square-o' => '? fa-check-square-o',
                            'fa-chevron-circle-down' => '? fa-chevron-circle-down',
                            'fa-chevron-circle-left' => '? fa-chevron-circle-left',
                            'fa-chevron-circle-right' => '? fa-chevron-circle-right',
                            'fa-chevron-circle-up' => '? fa-chevron-circle-up',
                            'fa-chevron-down' => '? fa-chevron-down',
                            'fa-chevron-left' => '? fa-chevron-left',
                            'fa-chevron-right' => '? fa-chevron-right',
                            'fa-chevron-up' => '? fa-chevron-up',
                            'fa-child' => '? fa-child',
                            'fa-circle' => '? fa-circle',
                            'fa-circle-o' => '? fa-circle-o',
                            'fa-circle-o-notch' => '? fa-circle-o-notch',
                            'fa-circle-thin' => '? fa-circle-thin',
                            'fa-clipboard' => '? fa-clipboard',
                            'fa-clock-o' => '? fa-clock-o',
                            'fa-close' => '? fa-close',
                            'fa-cloud' => '? fa-cloud',
                            'fa-cloud-download' => '? fa-cloud-download',
                            'fa-cloud-upload' => '? fa-cloud-upload',
                            'fa-cny' => '? fa-cny',
                            'fa-code' => '? fa-code',
                            'fa-code-fork' => '? fa-code-fork',
                            'fa-codepen' => '? fa-codepen',
                            'fa-coffee' => '? fa-coffee',
                            'fa-cog' => '? fa-cog',
                            'fa-cogs' => '? fa-cogs',
                            'fa-columns' => '? fa-columns',
                            'fa-comment' => '? fa-comment',
                            'fa-comment-o' => '? fa-comment-o',
                            'fa-comments' => '? fa-comments',
                            'fa-comments-o' => '? fa-comments-o',
                            'fa-compass' => '? fa-compass',
                            'fa-compress' => '? fa-compress',
                            'fa-copy' => '? fa-copy',
                            'fa-copyright' => '? fa-copyright',
                            'fa-credit-card' => '? fa-credit-card',
                            'fa-crop' => '? fa-crop',
                            'fa-crosshairs' => '? fa-crosshairs',
                            'fa-css3' => '? fa-css3',
                            'fa-cube' => '? fa-cube',
                            'fa-cubes' => '? fa-cubes',
                            'fa-cut' => '? fa-cut',
                            'fa-cutlery' => '? fa-cutlery',
                            'fa-dashboard' => '? fa-dashboard',
                            'fa-database' => '? fa-database',
                            'fa-dedent' => '? fa-dedent',
                            'fa-delicious' => '? fa-delicious',
                            'fa-desktop' => '? fa-desktop',
                            'fa-deviantart' => '? fa-deviantart',
                            'fa-digg' => '? fa-digg',
                            'fa-dollar' => '? fa-dollar',
                            'fa-dot-circle-o' => '? fa-dot-circle-o',
                            'fa-download' => '? fa-download',
                            'fa-dribbble' => '? fa-dribbble',
                            'fa-dropbox' => '? fa-dropbox',
                            'fa-drupal' => '? fa-drupal',
                            'fa-edit' => '? fa-edit',
                            'fa-eject' => '? fa-eject',
                            'fa-ellipsis-h' => '? fa-ellipsis-h',
                            'fa-ellipsis-v' => '? fa-ellipsis-v',
                            'fa-empire' => '? fa-empire',
                            'fa-envelope' => '? fa-envelope',
                            'fa-envelope-o' => '? fa-envelope-o',
                            'fa-envelope-square' => '? fa-envelope-square',
                            'fa-eraser' => '? fa-eraser',
                            'fa-eur' => '? fa-eur',
                            'fa-euro' => '? fa-euro',
                            'fa-exchange' => '? fa-exchange',
                            'fa-exclamation' => '? fa-exclamation',
                            'fa-exclamation-circle' => '? fa-exclamation-circle',
                            'fa-exclamation-triangle' => '? fa-exclamation-triangle',
                            'fa-expand' => '? fa-expand',
                            'fa-external-link' => '? fa-external-link',
                            'fa-external-link-square' => '? fa-external-link-square',
                            'fa-eye' => '? fa-eye',
                            'fa-eye-slash' => '? fa-eye-slash',
                            'fa-eyedropper' => '? fa-eyedropper',
                            'fa-facebook' => '? fa-facebook',
                            'fa-facebook-square' => '? fa-facebook-square',
                            'fa-fast-backward' => '? fa-fast-backward',
                            'fa-fast-forward' => '? fa-fast-forward',
                            'fa-fax' => '? fa-fax',
                            'fa-female' => '? fa-female',
                            'fa-fighter-jet' => '? fa-fighter-jet',
                            'fa-file' => '? fa-file',
                            'fa-file-archive-o' => '? fa-file-archive-o',
                            'fa-file-audio-o' => '? fa-file-audio-o',
                            'fa-file-code-o' => '? fa-file-code-o',
                            'fa-file-excel-o' => '? fa-file-excel-o',
                            'fa-file-image-o' => '? fa-file-image-o',
                            'fa-file-movie-o' => '? fa-file-movie-o',
                            'fa-file-o' => '? fa-file-o',
                            'fa-file-pdf-o' => '? fa-file-pdf-o',
                            'fa-file-photo-o' => '? fa-file-photo-o',
                            'fa-file-picture-o' => '? fa-file-picture-o',
                            'fa-file-powerpoint-o' => '? fa-file-powerpoint-o',
                            'fa-file-sound-o' => '? fa-file-sound-o',
                            'fa-file-text' => '? fa-file-text',
                            'fa-file-text-o' => '? fa-file-text-o',
                            'fa-file-video-o' => '? fa-file-video-o',
                            'fa-file-word-o' => '? fa-file-word-o',
                            'fa-file-zip-o' => '? fa-file-zip-o',
                            'fa-files-o' => '? fa-files-o',
                            'fa-film' => '? fa-film',
                            'fa-filter' => '? fa-filter',
                            'fa-fire' => '? fa-fire',
                            'fa-fire-extinguisher' => '? fa-fire-extinguisher',
                            'fa-flag' => '? fa-flag',
                            'fa-flag-checkered' => '? fa-flag-checkered',
                            'fa-flag-o' => '? fa-flag-o',
                            'fa-flash' => '? fa-flash',
                            'fa-flask' => '? fa-flask',
                            'fa-flickr' => '? fa-flickr',
                            'fa-floppy-o' => '? fa-floppy-o',
                            'fa-folder' => '? fa-folder',
                            'fa-folder-o' => '? fa-folder-o',
                            'fa-folder-open' => '? fa-folder-open',
                            'fa-folder-open-o' => '? fa-folder-open-o',
                            'fa-font' => '? fa-font',
                            'fa-forward' => '? fa-forward',
                            'fa-foursquare' => '? fa-foursquare',
                            'fa-frown-o' => '? fa-frown-o',
                            'fa-futbol-o' => '? fa-futbol-o',
                            'fa-gamepad' => '? fa-gamepad',
                            'fa-gavel' => '? fa-gavel',
                            'fa-gbp' => '? fa-gbp',
                            'fa-ge' => '? fa-ge',
                            'fa-gear' => '? fa-gear',
                            'fa-gears' => '? fa-gears',
                            'fa-gift' => '? fa-gift',
                            'fa-git' => '? fa-git',
                            'fa-git-square' => '? fa-git-square',
                            'fa-github' => '? fa-github',
                            'fa-github-alt' => '? fa-github-alt',
                            'fa-github-square' => '? fa-github-square',
                            'fa-gittip' => '? fa-gittip',
                            'fa-glass' => '? fa-glass',
                            'fa-globe' => '? fa-globe',
                            'fa-google' => '? fa-google',
                            'fa-google-plus' => '? fa-google-plus',
                            'fa-google-plus-square' => '? fa-google-plus-square',
                            'fa-google-wallet' => '? fa-google-wallet',
                            'fa-graduation-cap' => '? fa-graduation-cap',
                            'fa-group' => '? fa-group',
                            'fa-h-square' => '? fa-h-square',
                            'fa-hacker-news' => '? fa-hacker-news',
                            'fa-hand-o-down' => '? fa-hand-o-down',
                            'fa-hand-o-left' => '? fa-hand-o-left',
                            'fa-hand-o-right' => '? fa-hand-o-right',
                            'fa-hand-o-up' => '? fa-hand-o-up',
                            'fa-hdd-o' => '? fa-hdd-o',
                            'fa-header' => '? fa-header',
                            'fa-headphones' => '? fa-headphones',
                            'fa-heart' => '? fa-heart',
                            'fa-heart-o' => '? fa-heart-o',
                            'fa-history' => '? fa-history',
                            'fa-home' => '? fa-home',
                            'fa-hospital-o' => '? fa-hospital-o',
                            'fa-html5' => '? fa-html5',
                            'fa-ils' => '? fa-ils',
                            'fa-image' => '? fa-image',
                            'fa-inbox' => '? fa-inbox',
                            'fa-indent' => '? fa-indent',
                            'fa-info' => '? fa-info',
                            'fa-info-circle' => '? fa-info-circle',
                            'fa-inr' => '? fa-inr',
                            'fa-instagram' => '? fa-instagram',
                            'fa-institution' => '? fa-institution',
                            'fa-ioxhost' => '? fa-ioxhost',
                            'fa-italic' => '? fa-italic',
                            'fa-joomla' => '? fa-joomla',
                            'fa-jpy' => '? fa-jpy',
                            'fa-jsfiddle' => '? fa-jsfiddle',
                            'fa-key' => '? fa-key',
                            'fa-keyboard-o' => '? fa-keyboard-o',
                            'fa-krw' => '? fa-krw',
                            'fa-language' => '? fa-language',
                            'fa-laptop' => '? fa-laptop',
                            'fa-lastfm' => '? fa-lastfm',
                            'fa-lastfm-square' => '? fa-lastfm-square',
                            'fa-leaf' => '? fa-leaf',
                            'fa-legal' => '? fa-legal',
                            'fa-lemon-o' => '? fa-lemon-o',
                            'fa-level-down' => '? fa-level-down',
                            'fa-level-up' => '? fa-level-up',
                            'fa-life-bouy' => '? fa-life-bouy',
                            'fa-life-buoy' => '? fa-life-buoy',
                            'fa-life-ring' => '? fa-life-ring',
                            'fa-life-saver' => '? fa-life-saver',
                            'fa-lightbulb-o' => '? fa-lightbulb-o',
                            'fa-line-chart' => '? fa-line-chart',
                            'fa-link' => '? fa-link',
                            'fa-linkedin' => '? fa-linkedin',
                            'fa-linkedin-square' => '? fa-linkedin-square',
                            'fa-linux' => '? fa-linux',
                            'fa-list' => '? fa-list',
                            'fa-list-alt' => '? fa-list-alt',
                            'fa-list-ol' => '? fa-list-ol',
                            'fa-list-ul' => '? fa-list-ul',
                            'fa-location-arrow' => '? fa-location-arrow',
                            'fa-lock' => '? fa-lock',
                            'fa-long-arrow-down' => '? fa-long-arrow-down',
                            'fa-long-arrow-left' => '? fa-long-arrow-left',
                            'fa-long-arrow-right' => '? fa-long-arrow-right',
                            'fa-long-arrow-up' => '? fa-long-arrow-up',
                            'fa-magic' => '? fa-magic',
                            'fa-magnet' => '? fa-magnet',
                            'fa-mail-forward' => '? fa-mail-forward',
                            'fa-mail-reply' => '? fa-mail-reply',
                            'fa-mail-reply-all' => '? fa-mail-reply-all',
                            'fa-male' => '? fa-male',
                            'fa-map-marker' => '? fa-map-marker',
                            'fa-maxcdn' => '? fa-maxcdn',
                            'fa-meanpath' => '? fa-meanpath',
                            'fa-medkit' => '? fa-medkit',
                            'fa-meh-o' => '? fa-meh-o',
                            'fa-microphone' => '? fa-microphone',
                            'fa-microphone-slash' => '? fa-microphone-slash',
                            'fa-minus' => '? fa-minus',
                            'fa-minus-circle' => '? fa-minus-circle',
                            'fa-minus-square' => '? fa-minus-square',
                            'fa-minus-square-o' => '? fa-minus-square-o',
                            'fa-mobile' => '? fa-mobile',
                            'fa-mobile-phone' => '? fa-mobile-phone',
                            'fa-money' => '? fa-money',
                            'fa-moon-o' => '? fa-moon-o',
                            'fa-mortar-board' => '? fa-mortar-board',
                            'fa-music' => '? fa-music',
                            'fa-navicon' => '? fa-navicon',
                            'fa-newspaper-o' => '? fa-newspaper-o',
                            'fa-openid' => '? fa-openid',
                            'fa-outdent' => '? fa-outdent',
                            'fa-pagelines' => '? fa-pagelines',
                            'fa-paint-brush' => '? fa-paint-brush',
                            'fa-paper-plane' => '? fa-paper-plane',
                            'fa-paper-plane-o' => '? fa-paper-plane-o',
                            'fa-paperclip' => '? fa-paperclip',
                            'fa-paragraph' => '? fa-paragraph',
                            'fa-paste' => '? fa-paste',
                            'fa-pause' => '? fa-pause',
                            'fa-paw' => '? fa-paw',
                            'fa-paypal' => '? fa-paypal',
                            'fa-pencil' => '? fa-pencil',
                            'fa-pencil-square' => '? fa-pencil-square',
                            'fa-pencil-square-o' => '? fa-pencil-square-o',
                            'fa-phone' => '? fa-phone',
                            'fa-phone-square' => '? fa-phone-square',
                            'fa-photo' => '? fa-photo',
                            'fa-picture-o' => '? fa-picture-o',
                            'fa-pie-chart' => '? fa-pie-chart',
                            'fa-pied-piper' => '? fa-pied-piper',
                            'fa-pied-piper-alt' => '? fa-pied-piper-alt',
                            'fa-pinterest' => '? fa-pinterest',
                            'fa-pinterest-square' => '? fa-pinterest-square',
                            'fa-plane' => '? fa-plane',
                            'fa-play' => '? fa-play',
                            'fa-play-circle' => '? fa-play-circle',
                            'fa-play-circle-o' => '? fa-play-circle-o',
                            'fa-plug' => '? fa-plug',
                            'fa-plus' => '? fa-plus',
                            'fa-plus-circle' => '? fa-plus-circle',
                            'fa-plus-square' => '? fa-plus-square',
                            'fa-plus-square-o' => '? fa-plus-square-o',
                            'fa-power-off' => '? fa-power-off',
                            'fa-print' => '? fa-print',
                            'fa-puzzle-piece' => '? fa-puzzle-piece',
                            'fa-qq' => '? fa-qq',
                            'fa-qrcode' => '? fa-qrcode',
                            'fa-question' => '? fa-question',
                            'fa-question-circle' => '? fa-question-circle',
                            'fa-quote-left' => '? fa-quote-left',
                            'fa-quote-right' => '? fa-quote-right',
                            'fa-ra' => '? fa-ra',
                            'fa-random' => '? fa-random',
                            'fa-rebel' => '? fa-rebel',
                            'fa-recycle' => '? fa-recycle',
                            'fa-reddit' => '? fa-reddit',
                            'fa-reddit-square' => '? fa-reddit-square',
                            'fa-refresh' => '? fa-refresh',
                            'fa-remove' => '? fa-remove',
                            'fa-renren' => '? fa-renren',
                            'fa-reorder' => '? fa-reorder',
                            'fa-repeat' => '? fa-repeat',
                            'fa-reply' => '? fa-reply',
                            'fa-reply-all' => '? fa-reply-all',
                            'fa-retweet' => '? fa-retweet',
                            'fa-rmb' => '? fa-rmb',
                            'fa-road' => '? fa-road',
                            'fa-rocket' => '? fa-rocket',
                            'fa-rotate-left' => '? fa-rotate-left',
                            'fa-rotate-right' => '? fa-rotate-right',
                            'fa-rouble' => '? fa-rouble',
                            'fa-rss' => '? fa-rss',
                            'fa-rss-square' => '? fa-rss-square',
                            'fa-rub' => '? fa-rub',
                            'fa-ruble' => '? fa-ruble',
                            'fa-rupee' => '? fa-rupee',
                            'fa-save' => '? fa-save',
                            'fa-scissors' => '? fa-scissors',
                            'fa-search' => '? fa-search',
                            'fa-search-minus' => '? fa-search-minus',
                            'fa-search-plus' => '? fa-search-plus',
                            'fa-send' => '? fa-send',
                            'fa-send-o' => '? fa-send-o',
                            'fa-share' => '? fa-share',
                            'fa-share-alt' => '? fa-share-alt',
                            'fa-share-alt-square' => '? fa-share-alt-square',
                            'fa-share-square' => '? fa-share-square',
                            'fa-share-square-o' => '? fa-share-square-o',
                            'fa-shekel' => '? fa-shekel',
                            'fa-sheqel' => '? fa-sheqel',
                            'fa-shield' => '? fa-shield',
                            'fa-shopping-cart' => '? fa-shopping-cart',
                            'fa-sign-in' => '? fa-sign-in',
                            'fa-sign-out' => '? fa-sign-out',
                            'fa-signal' => '? fa-signal',
                            'fa-sitemap' => '? fa-sitemap',
                            'fa-skype' => '? fa-skype',
                            'fa-slack' => '? fa-slack',
                            'fa-sliders' => '? fa-sliders',
                            'fa-slideshare' => '? fa-slideshare',
                            'fa-smile-o' => '? fa-smile-o',
                            'fa-soccer-ball-o' => '? fa-soccer-ball-o',
                            'fa-sort' => '? fa-sort',
                            'fa-sort-alpha-asc' => '? fa-sort-alpha-asc',
                            'fa-sort-alpha-desc' => '? fa-sort-alpha-desc',
                            'fa-sort-amount-asc' => '? fa-sort-amount-asc',
                            'fa-sort-amount-desc' => '? fa-sort-amount-desc',
                            'fa-sort-asc' => '? fa-sort-asc',
                            'fa-sort-desc' => '? fa-sort-desc',
                            'fa-sort-down' => '? fa-sort-down',
                            'fa-sort-numeric-asc' => '? fa-sort-numeric-asc',
                            'fa-sort-numeric-desc' => '? fa-sort-numeric-desc',
                            'fa-sort-up' => '? fa-sort-up',
                            'fa-soundcloud' => '? fa-soundcloud',
                            'fa-space-shuttle' => '? fa-space-shuttle',
                            'fa-spinner' => '? fa-spinner',
                            'fa-spoon' => '? fa-spoon',
                            'fa-spotify' => '? fa-spotify',
                            'fa-square' => '? fa-square',
                            'fa-square-o' => '? fa-square-o',
                            'fa-stack-exchange' => '? fa-stack-exchange',
                            'fa-stack-overflow' => '? fa-stack-overflow',
                            'fa-star' => '? fa-star',
                            'fa-star-half' => '? fa-star-half',
                            'fa-star-half-empty' => '? fa-star-half-empty',
                            'fa-star-half-full' => '? fa-star-half-full',
                            'fa-star-half-o' => '? fa-star-half-o',
                            'fa-star-o' => '? fa-star-o',
                            'fa-steam' => '? fa-steam',
                            'fa-steam-square' => '? fa-steam-square',
                            'fa-step-backward' => '? fa-step-backward',
                            'fa-step-forward' => '? fa-step-forward',
                            'fa-stethoscope' => '? fa-stethoscope',
                            'fa-stop' => '? fa-stop',
                            'fa-strikethrough' => '? fa-strikethrough',
                            'fa-stumbleupon' => '? fa-stumbleupon',
                            'fa-stumbleupon-circle' => '? fa-stumbleupon-circle',
                            'fa-subscript' => '? fa-subscript',
                            'fa-suitcase' => '? fa-suitcase',
                            'fa-sun-o' => '? fa-sun-o',
                            'fa-superscript' => '? fa-superscript',
                            'fa-support' => '? fa-support',
                            'fa-table' => '? fa-table',
                            'fa-tablet' => '? fa-tablet',
                            'fa-tachometer' => '? fa-tachometer',
                            'fa-tag' => '? fa-tag',
                            'fa-tags' => '? fa-tags',
                            'fa-tasks' => '? fa-tasks',
                            'fa-taxi' => '? fa-taxi',
                            'fa-tencent-weibo' => '? fa-tencent-weibo',
                            'fa-terminal' => '? fa-terminal',
                            'fa-text-height' => '? fa-text-height',
                            'fa-text-width' => '? fa-text-width',
                            'fa-th' => '? fa-th',
                            'fa-th-large' => '? fa-th-large',
                            'fa-th-list' => '? fa-th-list',
                            'fa-thumb-tack' => '? fa-thumb-tack',
                            'fa-thumbs-down' => '? fa-thumbs-down',
                            'fa-thumbs-o-down' => '? fa-thumbs-o-down',
                            'fa-thumbs-o-up' => '? fa-thumbs-o-up',
                            'fa-thumbs-up' => '? fa-thumbs-up',
                            'fa-ticket' => '? fa-ticket',
                            'fa-times' => '? fa-times',
                            'fa-times-circle' => '? fa-times-circle',
                            'fa-times-circle-o' => '? fa-times-circle-o',
                            'fa-tint' => '? fa-tint',
                            'fa-toggle-down' => '? fa-toggle-down',
                            'fa-toggle-left' => '? fa-toggle-left',
                            'fa-toggle-off' => '? fa-toggle-off',
                            'fa-toggle-on' => '? fa-toggle-on',
                            'fa-toggle-right' => '? fa-toggle-right',
                            'fa-toggle-up' => '? fa-toggle-up',
                            'fa-trash' => '? fa-trash',
                            'fa-trash-o' => '? fa-trash-o',
                            'fa-tree' => '? fa-tree',
                            'fa-trello' => '? fa-trello',
                            'fa-trophy' => '? fa-trophy',
                            'fa-truck' => '? fa-truck',
                            'fa-try' => '? fa-try',
                            'fa-tty' => '? fa-tty',
                            'fa-tumblr' => '? fa-tumblr',
                            'fa-tumblr-square' => '? fa-tumblr-square',
                            'fa-turkish-lira' => '? fa-turkish-lira',
                            'fa-twitch' => '? fa-twitch',
                            'fa-twitter' => '? fa-twitter',
                            'fa-twitter-square' => '? fa-twitter-square',
                            'fa-umbrella' => '? fa-umbrella',
                            'fa-underline' => '? fa-underline',
                            'fa-undo' => '? fa-undo',
                            'fa-university' => '? fa-university',
                            'fa-unlink' => '? fa-unlink',
                            'fa-unlock' => '? fa-unlock',
                            'fa-unlock-alt' => '? fa-unlock-alt',
                            'fa-unsorted' => '? fa-unsorted',
                            'fa-upload' => '? fa-upload',
                            'fa-usd' => '? fa-usd',
                            'fa-user' => '? fa-user',
                            'fa-user-md' => '? fa-user-md',
                            'fa-users' => '? fa-users',
                            'fa-video-camera' => '? fa-video-camera',
                            'fa-vimeo-square' => '? fa-vimeo-square',
                            'fa-vine' => '? fa-vine',
                            'fa-vk' => '? fa-vk',
                            'fa-volume-down' => '? fa-volume-down',
                            'fa-volume-off' => '? fa-volume-off',
                            'fa-volume-up' => '? fa-volume-up',
                            'fa-warning' => '? fa-warning',
                            'fa-wechat' => '? fa-wechat',
                            'fa-weibo' => '? fa-weibo',
                            'fa-weixin' => '? fa-weixin',
                            'fa-wheelchair' => '? fa-wheelchair',
                            'fa-wifi' => '? fa-wifi',
                            'fa-windows' => '? fa-windows',
                            'fa-won' => '? fa-won',
                            'fa-wordpress' => '? fa-wordpress',
                            'fa-wrench' => '? fa-wrench',
                            'fa-xing' => '? fa-xing',
                            'fa-xing-square' => '? fa-xing-square',
                            'fa-yahoo' => '? fa-yahoo',
                            'fa-yelp' => '? fa-yelp',
                            'fa-yen' => '? fa-yen',
                            'fa-youtube' => '? fa-youtube',
                            'fa-youtube-play' => '? fa-youtube-play',
                            'fa-youtube-square' => '? fa-youtube-square',
                        ),
                    ),
                    array(
                        'key' => 'field_5433924100384',
                        'label' => 'Länka till',
                        'name' => 'af-menu-link-type',
                        'type' => 'select',
                        'column_width' => '',
                        'choices' => array(
                            'internal' => 'Lokal sida',
                            'external' => 'Extern sida',
                            'file' => 'Fil / Media',
                        ),
                        'default_value' => 'internal',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_543392d900386',
                        'label' => 'Lokal Sida',
                        'name' => 'af-menu-link-page',
                        'type' => 'page_link',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_5433924100384',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'post_type' => array(
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_543392f700387',
                        'label' => 'Extern URL',
                        'name' => 'af-menu-link-url',
                        'type' => 'text',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_5433924100384',
                                    'operator' => '==',
                                    'value' => 'external',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5433930c00388',
                        'label' => 'Fil',
                        'name' => 'af-menu-link-file',
                        'type' => 'file',
                        'conditional_logic' => array(
                            'status' => 1,
                            'rules' => array(
                                array(
                                    'field' => 'field_5433924100384',
                                    'operator' => '==',
                                    'value' => 'file',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'save_format' => 'object',
                        'library' => 'all',
                    ),
                    array(
                        "key" => "field_afmenulinktarget08yaf7ga9uf897agf79",
                        "label" => "Öppna länk i",
                        "name" => "af-menu-link-target",
                        "type" => "radio",
                        "choices" => array(
                            "_self" => "Samma fönster",
                            "_blank" => "Nytt fönster",
                            "lightbox" => "Lightbox"
                        ),
                    ),
                ),
                'row_min' => '',
                'row_limit' => 5,
                'layout' => 'row',
                'button_label' => 'Lägg till länk',
            ),
            array(
                'key' => 'field_5444ebc547298',
                'label' => 'Länkar/Sociala medier',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                "key" => "field_kugasdd987ywe3orjbn908734t",
                "label" => "Rubrik",
                "name" => "af-social-media-header",
                "type" => "text"
            ),
            array(
                'key' => 'field_5444ebd047299',
                'label' => 'Länkar till Sociala medier',
                'name' => 'af-social-media',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5444ebf94729a',
                        'label' => 'Ikon',
                        'name' => 'af-social-media-type',
                        'type' => 'font-awesome',
                        'column_width' => '',
                        'choices' => require("font-awesome-choices/font-awesome-choices.php"),
                        'default_value' => 'fa-facebook',
                        'save_format' => 'class',
                    ),
                    array(
                        'key' => 'field_5444f32a07760',
                        'label' => 'Länktext',
                        'name' => 'af-social-media-text',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5444ec584729b',
                        'label' => 'Länkadress',
                        'name' => 'af-social-media-url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till länk',
            ),
            array(
                'key' => 'field_54464102e9a02',
                'label' => 'Startsida',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_54464118e9a03',
                'label' => 'Snabblänkar',
                'name' => 'af-frontpage-shortlinks',
                'type' => 'relationship',
                'return_format' => 'object',
                'post_type' => array(
                    0 => 'shortlink',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'filters' => array(
                    0 => 'search',
                ),
                'result_elements' => array(
                    0 => 'post_title',
                ),
                'max' => 8,
            ),
            array(
                'key' => 'field_544f586793c80',
                'label' => 'Senaste på lager',
                'name' => 'af-car-tab-latest',
                'type' => 'post_object',
                'post_type' => array(
                    0 => 'assortment',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_544f58fc93c81',
                'label' => 'Månadens Star-Class',
                'name' => 'af-car-tab-star-class',
                'type' => 'post_object',
                'post_type' => array(
                    0 => 'assortment',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_544f5bd402b8f',
                'label' => 'Sökfunktion',
                'name' => 'af-car-tab-search',
                'type' => 'post_object',
                'post_type' => array(
                    0 => 'assortment',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_547471ed54c93',
                'label' => 'Återförsäljarens bildspel',
                'name' => 'af-slideshow',
                'type' => 'post_object',
                'post_type' => array(
                    0 => 'af_slideshow',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5446179e88927',
                'label' => 'Menyer',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_5449820w0h8f23408hy38928',
                'label' => 'Huvudmeny',
                'name' => 'af_settings_menu',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_544+9sv+nm0wh89v4348929',
                        'label' => 'Menyval',
                        'name' => 'af_settings_menu_item',
                        'type' => 'post_object',
                        'column_width' => '',
                        'post_type' => array(
                            0 => 'page',
                            1 => 'menus',
                        ),
                        'taxonomy' => array(
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till menyval',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-aterforsaljare-installningar',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}


?>
