<?php
add_action('init', 'cptui_register_my_cpt_accessory');
function cptui_register_my_cpt_accessory()
{
    register_post_type('accessory', array(
        'label' => 'Tillbehör',
        'description' => '',
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => array('slug' => 'accessory', 'with_front' => true),
        'query_var' => true,
        'supports' => array('title', 'custom-fields', 'revisions'),
        'taxonomies' => array('brand', 'utrustning'),
        'labels' => array(
            'name' => 'Tillbehör',
            'singular_name' => 'Tillbehör',
            'menu_name' => 'Tillbehör',
            'add_new' => 'Add Tillbehör',
            'add_new_item' => 'Add New Tillbehör',
            'edit' => 'Edit',
            'edit_item' => 'Edit Tillbehör',
            'new_item' => 'New Tillbehör',
            'view' => 'View Tillbehör',
            'view_item' => 'View Tillbehör',
            'search_items' => 'Search Tillbehör',
            'not_found' => 'No Tillbehör Found',
            'not_found_in_trash' => 'No Tillbehör Found in Trash',
            'parent' => 'Parent Tillbehör',
        )
    ));
}

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_produkt',
        'title' => 'Produkt',
        'fields' => array(
            array(
                'key' => 'field_551239be69730',
                'label' => 'Bild',
                'name' => 'accessory-image',
                'type' => 'image_crop',
				'crop_type' => 'hard',
				'target_size' => 'accesory-default',
				'width' => '',
				'height' => '',
				'preview_size' => 'accesory-sd',
				'force_crop' => 'yes',
				'save_in_media_library' => 'no',
				'retina_mode' => 'no',
				'save_format' => 'object',
                'library' => 'all',
            ),
            array(
                'key' => 'field_551239216972b',
                'label' => 'Namn',
                'name' => 'accessory-name',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5512392f6972c',
                'label' => 'Modell',
                'name' => 'accessory-model',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_551239416972d',
                'label' => 'Specifikation',
                'name' => 'accessory-specification',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_551232a16973a',
                'label' => 'Pristyp',
                'name' => 'accessory-prices',
				'type' => 'repeater',
				'instructions' => 'Lägg till de priser som skall visas för tillbehöret.',
				'sub_fields' => array (
					array (
						'key' => 'field_5512e32a16973a',
						'label' => 'Pristyp',
						'name' => 'accessory-price-type',
						'type' => 'post_object',
						'instructions' => 'Välj en pristyp du vill visa priset som.',
						'column_width' => 50,
						'post_type' => array (
							0 => 'offer_price',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_551212cef9aa',
						'label' => 'Pris',
						'name' => 'accessory-price-value',
						'type' => 'text',
						'instructions' => 'Fyll i det pris eller text du vill visa.',
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Lägg till pris',
			),
            array(
                'key' => 'field_55121583697fa',
                'label' => 'Beskrivning',
                'name' => 'accessory-description',
                'type' => 'wysiwyg',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'no',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'accessory',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
                0 => 'excerpt',
                1 => 'custom_fields',
                2 => 'discussion',
                3 => 'comments',
                4 => 'slug',
                5 => 'author',
                6 => 'format',
                7 => 'featured_image',
                8 => 'categories',
                9 => 'tags',
                10 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}

?>
