<?php

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_sidans-innehall',
        'title' => 'Sidans innehåll',
        'fields' => array(
            array(
                'key' => 'field_551b89a927ee5',
                'label' => 'Rad',
                'name' => 'row',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_551b97691e918',
                        'label' => 'Inställningar',
                        'name' => 'row-settings',
                        'type' => 'checkbox',
                        'column_width' => '',
                        'choices' => array(
                            'on' => '',
                        ),
                        'default_value' => '',
                        'layout' => 'vertical',
                    ),
                    array (
                        'key' => 'field_551b89e827ee7',
                        'label' => 'Innehåll',
                        'name' => 'row-content',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array (
                            array(
                                'key' => 'field_5576c7b1a6871',
                                'label' => 'Layout',
                                'name' => 'content-layout',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'block' => 'Block',
                                    'custom' => 'Eget innehåll',
                                    'employees' => 'Personal',
                                    'equipment' => 'Utrusning',
                                    'facility' => 'Anläggningskort',
                                    'form' => 'Formulär',
                                    'news' => 'Nyhetsblock',
                                    'offers' => 'Erbjudanden',
                                    'open_hours' => 'Öppettider',
                                    'section' => 'Befintlig sektion',
                                    'slideshow' => 'Bildspel',
                                    'vehicle' => 'Bilmodeller',
                                    'accesspackage' => 'Fordonsurval'
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_52j43fr80utr34083',
                                'label' => 'Sökmotor',
                                'name' => 'accesspackage-search-type',
                                'type' => 'select',
                                'choices' => array(
                                    'Search' => 'Sökfunktion',
                                    'FreeTextSearch' => 'Fritextsök',
                                    'none' => 'Ingen'
                                )
                            ),
                            array(
                                'key' => 'field_uer83458723hfw',
                                'name' => 'accesspackage-search-bg',
                                'label' => 'Bakgrundsbild (sökmotor)',
                                'type' => 'image',
                                'save_format' => 'object'
                            ),
                            array(
                                'key' => 'field_ut523urt834596aaa23gew47652',
                                'label' => 'Lås fordonsurval',
                                'name' => 'accesspackage-lock',
                                'type' => 'true_false',
                            ),
                            array(
                                'key' => 'field_ut523urt83459623gew47652',
                                'label' => 'Visa filtreringsfunktion',
                                'name' => 'accesspackage-filter',
                                'type' => 'true_false',
                            ),
                            array(
                                'key' => 'field_uturt8345962347652',
                                'label' => 'Visa billista',
                                'name' => 'accesspackage-list',
                                'type' => 'true_false',
                            ),
//                            array(
//                                'key' => 'field_2384572398wqhuerfh',
//                                'label' => 'Vy',
//                                'name' => 'accesspackage-view-picker',
//                                'type' => 'checkbox',
//                                'choices' => array(
//                                    'search' => 'Sökmotor',
//                                    'freetextsearch' => 'Fritextsök',
//                                    'filter' => 'Filtrering',
//                                    'list' => 'Lista'
//                                ),
//                                'layout' => 'vertical',
//                                'column_width' => '',
//                            ),
                            array(
                                'key' => 'field_43409324jre495',
                                'label' => 'Landningssida (sökmotor)',
                                'name' => 'accesspackage-page',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array(
                                    0 => 'page',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'allow_null' => 1,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_4324093s3346724jre495',
                                'label' => 'Landningssida (objekt)',
                                'name' => 'accesspackage-object-page',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array(
                                    0 => 'page',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'allow_null' => 1,
                                'multiple' => 0,
                            ),
//                            array(
//                                'key' => 'field_2809435y7u23123',
//                                'label' => 'Antal per sida',
//                                'name' => 'accesspackage-count',
//                                'type' => 'number',
//                                'column_width' => '',
//                            ),
                            array(
                                'key' => 'field_floj4380utr34083',
                                'label' => 'Ladda in fler fordon?',
                                'name' => 'accesspackage-load-type',
                                'type' => 'select',
                                'choices' => array(
                                    'None' => 'Ladda inte in fler fordon',
                                    'Infinite' => 'Ladda fler fordon vid scrollning',
                                    'Button' => 'Ladda in fler fordon genom en knapp'
                                )
                            ),
                            array(
                                'key' => 'field_5473239ef4634e996fd',
                                'name' => 'accesspackage-search',
                                'type' => 'message',
                                'message' => '<div data-app="elasticaccesspackage"><div ng-include src="\'templates/WP-Admin.html\'"></div></div>',
                            ),
                            array(
                                'key' => 'field_elasticaccess-hash',
                                'label' => '',
                                'name' => 'accesspackage-hash',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5546e4d4d4435',
                                'label' => 'Administrativ rubrik',
                                'name' => 'content-admin-header',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_45522427c877e',
                                'label' => 'Visa som flik',
                                'name' => 'content-tab',
                                'type' => 'radio',
                                'instructions' => 'Välj om du vill visa innehållet som en flik, och fyll i flikens titel eller använd den administrativa rubriken.',
                                'column_width' => '',
                                'choices' => array(
                                    'false' => 'Nej',
                                    'true' => 'Ja',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'false',
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_45522450c877f',
                                'label' => 'Fliktext',
                                'name' => 'content-tab-text',
                                'type' => 'text',
                                'instructions' => 'Välj om du vill visa innehållet som en flik, och fyll i flikens titel eller använd den administrativa rubriken.',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5520e83b1fe6f',
                                'label' => 'Bredd',
                                'name' => 'content-width',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array(
                                    100 => '100%',
                                    75 => '75%',
                                    66 => '66%',
                                    50 => '50%',
                                    33 => '33%',
                                    25 => '25%',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 100,
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_5520e8c91fe70',
                                'label' => 'Innehåll',
                                'name' => 'content-wysiwyg',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => 'Här kan du skriva i eget innehåll',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array(
                                'key' => 'field_5548c860883e0',
                                'label' => 'Anläggning',
                                'name' => 'content-facility',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array(
                                    0 => 'facility',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_55498e7293546',
                                'label' => 'Layout',
                                'name' => 'content-open-hours-layout',
                                'type' => 'select',
                                'instructions' => 'Välj hur du vill skriva ut öppettiderna.',
                                'column_width' => '',
                                'choices' => array(
                                    'block-icons' => 'Avdelningar med ikoner',
                                    'list-icons' => 'Avdelningar utan ikoner',
                                    'accordion' => 'Som en Widget',
                                    'facilites' => 'En Anläggningslista',
                                ),
                                'default_value' => 'block-icons',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5549906c93547',
                                'label' => 'Välj anläggning',
                                'name' => 'content-open-hours-facility',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'facility',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554990ad93548',
                                'label' => 'Välj avdelningar',
                                'name' => 'content-open-hours-department',
                                'type' => 'checkbox',
                                'instructions' => 'Välj de avdelningar du vill visa öppettider för',
                                'column_width' => '',
                                'choices' => array(
                                    'carsales' => 'Bilförsäljning',
                                    'store' => 'Butik och bildelar',
                                    'damage' => 'Skadecenter',
                                    'workshop' => 'Verkstad',
                                    'other' => 'En annan',
                                ),
                                'default_value' => '',
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_5549d31d41957',
                                'label' => 'Layout',
                                'name' => 'content-employee-layout',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'specific' => 'Välj personal',
                                    'list' => 'Personallista',
                                    'automatisk' => 'Automatisk lista',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5549b8a734a44',
                                'label' => 'Vilken personal',
                                'name' => 'content-employees-specific',
                                'type' => 'relationship',
                                'instructions' => 'Välj hur du vill visa personalen',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'employee',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_5549d36d41958',
                                'label' => 'Välj personallista',
                                'name' => 'content-employees-list',
                                'type' => 'relationship',
                                'instructions' => 'Välj hur du vill visa personalen',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'employee_list',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_type',
                                    1 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_5549b8a734a46',
                                'label' => 'Från avdelning',
                                'name' => 'content-employees-department',
                                'type' => 'checkbox',
                                'instructions' => 'Välj de avdelningar du vill visa öppettider för',
                                'column_width' => '',
                                'choices' => array(
                                    'carsales' => 'Bilförsäljning',
                                    'store' => 'Butik och bildelar',
                                    'damage' => 'Skadecenter',
                                    'workshop' => 'Verkstad',
                                    'other' => 'En annan',
                                ),
                                'default_value' => '',
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_5549ba6234a49',
                                'label' => 'Från anläggning',
                                'name' => 'content-employees-cities',
                                'type' => 'taxonomy',
                                'instructions' => 'Välj de avdelningar du vill visa öppettider för',
                                'column_width' => '',
                                'taxonomy' => 'cities',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5549d30041956',
                                'label' => 'För märke',
                                'name' => 'content-employees-brand',
                                'type' => 'taxonomy',
                                'instructions' => 'Välj de avdelningar du vill visa öppettider för',
                                'column_width' => '',
                                'taxonomy' => 'brand',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5549b9a734a48',
                                'label' => 'Dölj märke',
                                'name' => 'content-employees-hide-brand',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'true' => 'Dölj märkesinfo',
                                    'logotype' => 'Visa enbart logotyp',
                                    'text' => 'Visa enbart som text',
                                ),
                                'default_value' => 'true',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5549ec7a92c2f',
                                'label' => 'Använd slider',
                                'name' => 'content-slider',
                                'type' => 'checkbox',
                                'instructions' => 'Bestäm hur många personal som skall visas per rad',
                                'column_width' => '',
                                'choices' => array(
                                    'true' => 'Ja, visa som slider',
                                ),
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                            array(
                                'key' => 'field_5549ec5692c2e',
                                'label' => 'Antal per slide',
                                'name' => 'content-employees-paging',
                                'type' => 'number',
                                'instructions' => 'Bestäm hur många personal som skall visas per sida eller slide',
                                'column_width' => '',
                                'default_value' => 4,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_5550aabd27a4b',
                                'label' => 'Bildspelstyp',
                                'name' => 'content-slideshow-type',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'existing' => 'Befintligt',
                                    'offers' => 'Erbjudanden',
                                    'models' => 'Bilmodeller',
                                ),
                                'default_value' => 'existing',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5523e530e1b0d',
                                'label' => 'Bildspel',
                                'name' => 'content-existing-slideshow',
                                'type' => 'post_object',
                                'column_width' => '',
                                'post_type' => array(
                                    0 => 'slideshow',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5550ab3127a4c',
                                'label' => 'Vilka erbjudanden',
                                'name' => 'content-slideshow-offers',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array(
                                    'automatic' => 'Automatiskt',
                                    'specific' => 'Specifika',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'automatic',
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_5550ac9227a4d',
                                'label' => 'Från märke/modeller',
                                'name' => 'content-slideshow-brand',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'brand',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5550acbc27a4e',
                                'label' => 'Från anläggning',
                                'name' => 'content-slideshow-facility',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'cities',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5550b0a291eb0',
                                'label' => 'Av erbjudandetyp',
                                'name' => 'content-slideshow-offer-type',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'offer_type',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_5550aced27a4f',
                                'label' => 'Välj erbjudanden',
                                'name' => 'content-slideshow-offers-specific',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'offer',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_5551e25540e13',
                                'label' => 'Vilka modeller',
                                'name' => 'content-slideshow-model',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'vehicle',
                                    1 => 'modelgroup',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_type',
                                    1 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554840e002bb8',
                                'label' => 'Kontaktformulär',
                                'name' => 'content-existing-form',
                                'type' => 'acf_cf7',
                                'column_width' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'disable' => array(
                                    0 => 0,
                                ),
                            ),
                            array(
                                'key' => 'field_5548411802bb9',
                                'label' => 'Layout',
                                'name' => 'content-form-layout',
                                'type' => 'select',
                                'column_width' => '',
                                'choices' => array(
                                    'default' => 'Standard',
                                    'slider' => 'Slider',
                                    'step' => 'Flera Steg',
                                ),
                                'default_value' => 'default',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_552b692d015cc',
                                'label' => 'Bakgrundsfärg',
                                'name' => 'content-block-background',
                                'type' => 'color_picker',
                                'column_width' => '',
                                'default_value' => 'transparent',
                            ),
                            array(
                                'key' => 'field_552b68d16a700',
                                'label' => 'Innehåll',
                                'name' => 'content-block-contents',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                            array(
                                'key' => 'field_55407769970f2',
                                'label' => 'Skugga',
                                'name' => 'content-block-shadow',
                                'type' => 'select',
                                'instructions' => 'Välj en skuggeffekt du vill ha på blocket',
                                'column_width' => '',
                                'choices' => array(
                                    'none' => 'Ingen',
                                    'small' => 'Liten skugga',
                                    'big' => 'Stor skugga',
                                    'inside' => 'Skugga på insidan',
                                ),
                                'default_value' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_553dbfd3446b8',
                                'label' => 'Innehåll',
                                'name' => 'content-vehicle-contents',
                                'type' => 'select',
                                'instructions' => 'Välj vilket innehåll från Bilmodellen du vill visa.',
                                'column_width' => '',
                                'choices' => array(
                                    'info' => 'Modellinformation',
                                    'list' => 'Modelllista',
                                    'header' => 'Headerbild med beskrivning',
                                    'equipment' => 'Utrustning',
                                    'gallery' => 'Fotogalleri',
                                ),
                                'default_value' => 'info',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_553dc04f446b9',
                                'label' => 'Bilmodeller',
                                'name' => 'content-vehicle-model',
                                'type' => 'relationship',
                                'instructions' => 'Välj den bilmodell du vill visa information från.',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'vehicle',
                                    1 => 'modelgroup',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_type',
                                    1 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554a131c3c7ad',
                                'label' => 'Innehåll',
                                'name' => 'content-equipment-contents',
                                'type' => 'select',
                                'instructions' => 'Välj vilket innehåll från Bilmodellen du vill visa.',
                                'column_width' => '',
                                'choices' => array(
                                    'custom' => 'Egen lista',
                                    'package' => 'Utrustningspaket',
                                    'model' => 'Modell',
                                ),
                                'default_value' => 'custom',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_554a131c3c7ae',
                                'label' => 'Utrustning',
                                'name' => 'content-equipment',
                                'type' => 'relationship',
                                'instructions' => 'Välj den bilmodell du vill visa information från.',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'equipment',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                    1 => 'post_type',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554a13983c7af',
                                'label' => 'Utrustningspaket',
                                'name' => 'content-equipment-package',
                                'type' => 'relationship',
                                'instructions' => 'Välj det utrustningspaket du vill visa information från.',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'equipment_package',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                    1 => 'post_type',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554a13ca3c7b0',
                                'label' => 'Bilmodeller',
                                'name' => 'content-equipment-models',
                                'type' => 'relationship',
                                'instructions' => 'Välj de bilmodeller du vill visa utrustning från.',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'equipment_package',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                    1 => 'post_type',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_554850fb2b3b4',
                                'label' => 'Välj sektion',
                                'name' => 'content-section',
                                'type' => 'relationship',
                                'instructions' => 'Välj det märke du vill visa bilar från',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'section',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_555300f2f95dc',
                                'label' => 'Layout',
                                'name' => 'content-news-layout',
                                'type' => 'select',
                                'instructions' => 'Välj med vilken layout du vill visa nyhetsblocket',
                                'column_width' => '',
                                'choices' => array(
                                    'card-list' => 'Ett kort med lista',
                                    'cards' => 'Kort',
                                    'list' => 'Lista',
                                ),
                                'default_value' => 'card-list',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_555301ccf95dd',
                                'label' => 'Antal inlägg',
                                'name' => 'content-news-amount',
                                'type' => 'number',
                                'instructions' => 'Välj hur många inlägg du vill visa i nyhetsblocket.',
                                'column_width' => '',
                                'default_value' => 4,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_1250ab3127a4c',
                                'label' => 'Vilka erbjudanden',
                                'name' => 'content-offers-choice',
                                'type' => 'radio',
                                'column_width' => '',
                                'choices' => array(
                                    'specific' => 'Specifika',
                                    'automatic' => 'Automatiskt',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'specific',
                                'layout' => 'horizontal',
                            ),
                            array(
                                'key' => 'field_1250aced27a4f',
                                'label' => 'Välj erbjudanden',
                                'name' => 'content-offers-specific',
                                'type' => 'relationship',
                                'column_width' => '',
                                'return_format' => 'object',
                                'post_type' => array(
                                    0 => 'offer',
                                ),
                                'taxonomy' => array(
                                    0 => 'all',
                                ),
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'result_elements' => array(
                                    0 => 'post_title',
                                ),
                                'max' => '',
                            ),
                            array(
                                'key' => 'field_553f3f9618afb',
                                'label' => 'Från märke',
                                'name' => 'content-offer-brands',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'brand',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_553f3ff118afd',
                                'label' => 'Från anläggning',
                                'name' => 'content-offer-facility',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'cities',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_553f407318afe',
                                'label' => 'Av erbjudandetyp',
                                'name' => 'content-offer-type',
                                'type' => 'taxonomy',
                                'column_width' => '',
                                'taxonomy' => 'offer_type',
                                'field_type' => 'checkbox',
                                'allow_null' => 0,
                                'load_save_terms' => 0,
                                'return_format' => 'id',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_553f51eb12497',
                                'label' => 'Antal per rad',
                                'name' => 'content-offer-row',
                                'type' => 'number',
                                'column_width' => '',
                                'default_value' => 2,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_553f399c18af8',
                                'label' => 'Antal per sida',
                                'name' => 'content-offer-amount',
                                'type' => 'number',
                                'instructions' => 'Välj den erbjudandemodul du vill visa',
                                'column_width' => '',
                                'default_value' => 4,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'row',
                        'button_label' => 'Lägg till innehåll',
                    ),

                    array(
                        'key' => 'field_551be1b8736fd',
                        'label' => 'Menytitel',
                        'name' => 'row-settings-menu-header',
                        'type' => 'text',
                        'instructions' => 'Fyll i en titel som skall visas i sidans meny.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_55308e95431f2',
                        'label' => 'Radrubrik',
                        'name' => 'row-settings-heading',
                        'type' => 'text',
                        'instructions' => 'Fyll i om du vill visa en rubrik för raden',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_55531e769f046',
                        'label' => 'Radbeskrivning',
                        'name' => 'row-settings-paragraph',
                        'type' => 'wysiwyg',
                        'instructions' => 'Fyll i om du vill att raden skall ha en beskrivande text under rubriken.',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'basic',
                        'media_upload' => 'no',
                    ),
                    array(
                        'key' => 'field_551bdf15736f7',
                        'label' => 'Bredd',
                        'name' => 'row-settings-width',
                        'type' => 'radio',
                        'instructions' => 'Välj hur bred raden skall vara.',
                        'column_width' => '',
                        'choices' => array(
                            'wrapper' => 'Boxed (100%)',
                            'wrapper-75' => 'Boxed (75%)',
                            'wrapper-50' => 'Boxed (50%)',
                            'wrapper-25' => 'Boxed (25%)',
                            'full' => 'Fullbredd',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => 'wrapper',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_553098f374734',
                        'label' => 'Justering',
                        'name' => 'row-settings-float',
                        'type' => 'radio',
                        'instructions' => 'Välj hur bred raden skall vara.',
                        'column_width' => '',
                        'choices' => array(
                            'center' => 'Centrera',
                            'left' => 'Till vänster',
                            'right' => 'Till höger',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => 'center',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_553082101a075',
                        'label' => 'Padding',
                        'name' => 'row-settings-padding',
                        'type' => 'radio',
                        'instructions' => 'Välj hur mycket padding raden skall ha',
                        'column_width' => '',
                        'choices' => array(
                            'default-padding' => 'Standard (30px)',
                            'none-padding' => 'Ingen (0px)',
                            'large-padding' => 'Stor (60px)',
                            'small-padding' => 'Liten (15px)',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => 'default-padding',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_553dc4cb219ec',
                        'label' => 'Textfärg',
                        'name' => 'row-settings-text-color',
                        'type' => 'select',
                        'instructions' => 'Välj vilken textfärg dynamiskt innehåll skall ha i raden.',
                        'column_width' => '',
                        'choices' => array(
                            'dark' => 'Mörk',
                            'light' => 'Ljus',
                            '' => '',
                        ),
                        'default_value' => 'dark',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_551bdfeb736f8',
                        'label' => 'Bakgrund',
                        'name' => 'row-settings-background',
                        'type' => 'select',
                        'instructions' => 'Välj vad för bakgrund raden skall ha.',
                        'column_width' => '',
                        'choices' => array(
                            'color' => 'Färg',
                            'image' => 'Bild',
                            'video' => 'Video',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_551be097736fa',
                        'label' => 'Bakgrundsfärg',
                        'name' => 'row-settings-background-color',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken färg bakgrunden skall ha.',
                        'column_width' => '',
                        'default_value' => '#f7f7f7',
                    ),
                    array(
                        'key' => 'field_551be065736f9',
                        'label' => 'Bakgrundsbild',
                        'name' => 'row-settings-background-image',
                        'type' => 'image',
                        'instructions' => 'Ladda upp eller välj en bakgrundsbild för raden.',
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_551be0ff736fb',
                        'label' => 'Bakgrundseffekt',
                        'name' => 'row-settings-background-effect',
                        'type' => 'checkbox',
                        'instructions' => 'Bocka i om du vill använda en effekt på bakgrunden.',
                        'column_width' => '',
                        'choices' => array(
                            'fade' => 'Tona ut',
                            'overlay' => 'Overlay',
                            'border' => 'Ram',
                            'shadow' => 'Skugga',
                        ),
                        'default_value' => '',
                        'layout' => 'horizontal',
                    ),
                    array(
                        'key' => 'field_551be215736fe',
                        'label' => 'Tona ut',
                        'name' => 'row-settings-background-effect-fade',
                        'type' => 'select',
                        'instructions' => 'Välj en uttoningseffekt.',
                        'column_width' => '',
                        'choices' => array(
                            'left' => 'Till vänster',
                            'right' => 'Till höger',
                            'middle' => 'Från mitten',
                        ),
                        'default_value' => 'left',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_551be273736ff',
                        'label' => 'Färg',
                        'name' => 'row-settings-background-effect-fade-color',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken färg du vill bakgrunden skall tona ut i.',
                        'column_width' => '',
                        'default_value' => '#ffffff',
                    ),
                    array(
                        'key' => 'field_551be34c73701',
                        'label' => 'Overlayfärg',
                        'name' => 'row-settings-background-effect-overlay-color',
                        'type' => 'color_picker',
                        'instructions' => 'Välj en overlay-färg för bakgrunden.',
                        'column_width' => '',
                        'default_value' => '#ffffff',
                    ),
                    array(
                        'key' => 'field_551be2c373700',
                        'label' => 'Overlaystyrka',
                        'name' => 'row-settings-background-effect-overlay-opacity',
                        'type' => 'number',
                        'instructions' => 'Fyll i en styrka för overlayfärgen. Ju högre styrka desto mindre av bakgrunden syns.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '%',
                        'min' => 0,
                        'max' => 100,
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_551be38773702',
                        'label' => 'Ramfärg',
                        'name' => 'row-settings-background-effect-border-color',
                        'type' => 'color_picker',
                        'column_width' => '',
                        'default_value' => '#ffffff',
                    ),
                    array(
                        'key' => 'field_551be3b273703',
                        'label' => 'Skugga',
                        'name' => 'row-settings-background-effect-shadow',
                        'type' => 'select',
                        'instructions' => 'Välj en skuggtyp för raden.',
                        'column_width' => '',
                        'choices' => array(
                            'inner-big' => 'Insida stor',
                            'inner-small' => 'Insida liten',
                        ),
                        'default_value' => 'inner-big',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_55520a91e5eac',
                        'label' => 'Använd flikar',
                        'name' => 'row-settings-tabs',
                        'type' => 'select',
                        'instructions' => 'Välj om raden kommer använda flikar',
                        'column_width' => '',
                        'choices' => array(
                            'false' => 'Nej',
                            'true' => 'Ja',
                        ),
                        'default_value' => 'false',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_55485153e50ee',
                        'label' => 'Använd befintlig sektion',
                        'name' => 'row-settings-section',
                        'type' => 'relationship',
                        'column_width' => '',
                        'return_format' => 'object',
                        'post_type' => array(
                            0 => 'section',
                        ),
                        'taxonomy' => array(
                            0 => 'all',
                        ),
                        'filters' => array(
                            0 => 'search',
                        ),
                        'result_elements' => array(
                            0 => 'post_title',
                        ),
                        'max' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till rad',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'offer',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'section',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'slug',
                6 => 'author',
                7 => 'format',
                8 => 'categories',
                9 => 'tags',
                10 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 1,
    ));

    register_field_group(array(
        'id' => 'acf_sidans-installningar',
        'title' => 'Sidans inställningar',
        'fields' => array(
            array(
                'key' => 'field_553a2d02c7cda',
                'label' => 'Inställningar',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_553a2d1ac7cdb',
                'label' => 'Använd undermeny',
                'name' => 'page-settings-menu',
                'type' => 'true_false',
                'instructions' => 'Bocka i om du vill visa en undermeny på sidan för de olika raderna.',
                'message' => '',
                'default_value' => 1,
            ),
            array(
                'key' => 'field_553a2f7361736',
                'label' => 'Progress bar',
                'name' => 'page-settings-menu-bar',
                'type' => 'color_picker',
                'instructions' => 'Välj en färg som skall indikera vart på sidan man är i menyn.',
                'default_value' => '',
            ),
            array(
                'key' => 'field_553a2e2cc7cdc',
                'label' => 'SEO',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_553a30b361737',
                'label' => 'Avancerat',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_553a30c061738',
                'label' => 'CSS',
                'name' => 'page-settings-css',
                'type' => 'code_area',
                'instructions' => 'Fyll i om du vill att sidan skall läsa in egen CSS.',
                'language' => 'css',
                'theme' => 'solarized',
            ),
            array(
                'key' => 'field_553a30d161739',
                'label' => 'Javascript',
                'name' => 'page-settings-js',
                'type' => 'code_area',
                'instructions' => 'Fyll i om du vill att sidan skall köra egen Javascript.',
                'language' => 'javascript',
                'theme' => 'solarized',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'offer',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),            
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'slug',
                6 => 'author',
                7 => 'format',
                8 => 'featured_image',
                9 => 'categories',
                10 => 'tags',
                11 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 10,
    ));
}

?>

